In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.base import clone

import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn as nn

import os
from tqdm import tqdm
import random

from prepare_data import prepare_data
from preprocessor_function import preprocessor_function

In [2]:
#объявляем random.seed

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [3]:
#загружаем тренировочные данные
data = pd.read_csv('data/train.csv')
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
y = np.log1p(data['SalePrice'])
X = prepare_data(data.drop('SalePrice',axis=1))

In [5]:
#удаляем выбросы
X = X[X['GrLivArea'] < 4500]

In [6]:
#синхронизируем данные
y = y[X.index]

In [7]:
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.1, random_state=SEED)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=(0.2/0.9), random_state=SEED)

In [8]:
numeric_colums = X_train.select_dtypes(include=['number']).columns
categorical_colums = X_train.select_dtypes(include=['object', 'string']).columns

In [9]:
preprocessor = preprocessor_function(X_train, categorical_colums, numeric_colums)

In [ ]:
preview_preprocessor = clone(preprocessor).set_output(transform='pandas')
X_encoded_preview = preview_preprocessor.fit_transform(X, y)
X_encoded_preview.head()

,Street_Pave,Alley_Grvl,Alley_Pave,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,Utilities_NoSeWa,...,PoolArea,MiscVal,MoSold,YrSold,HouseAge,RemodAge,TotalBath,HasGarage,HasBasement,TotalSF
0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,-1.601578,0.138375,-1.045249,-0.871676,1.174852,0.242536,0.161363,0.011436
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,-0.490155,-0.614427,-0.185182,0.388660,0.386571,0.242536,0.161363,-0.042838
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,0.991743,0.138375,-0.979090,-0.823201,1.174852,0.242536,0.161363,0.192351
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,-1.601578,-1.367230,1.799589,0.631032,-1.189990,0.242536,0.161363,-0.108743
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,2.103167,0.138375,-0.946011,-0.726252,1.174852,0.242536,0.161363,1.015514

In [11]:
generator = torch.Generator().manual_seed(SEED)

# Применяем препроцессор
X_train_processed = preprocessor.fit_transform(X_train, y_train)
X_val_processed = preprocessor.transform(X_val)
X_test_processed = preprocessor.transform(X_test)

# Преобразуем данные в тензоры PyTorch
X_train_tensor = torch.tensor(X_train_processed, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1)

X_val_tensor = torch.tensor(X_val_processed, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32).unsqueeze(1)

X_test_tensor = torch.tensor(X_test_processed, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1)

# Создаем TensorDataset
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

# Создаем DataLoader'ы
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True, generator=generator)
val_loader = DataLoader(dataset=val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False)

c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [8, 9, 14, 15] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [ ]:
#создаем модель 
class MyNN(nn.Module):
    def __init__(self, input, output):
        super().__init__()
        self.layer_1 = nn.Linear(input,128)
        self.batch_norm_1 = nn.BatchNorm1d(128)
        self.act_1 = nn.LeakyReLU()
        self.dropout_1 = nn.Dropout(0.4)
        self.layer_2 = nn.Linear(128,64)
        self.batch_norm_2 = nn.BatchNorm1d(64)
        self.act_2 = nn.LeakyReLU()
        self.dropout_2 = nn.Dropout(0.2)
        self.layer_3 = nn.Linear(64,32)
        self.batch_norm_3 = nn.BatchNorm1d(32)
        self.act_3 = nn.ReLU()
        self.dropout_3 = nn.Dropout(0.3)
        self.layer_4 = nn.Linear(32,output)

    def forward(self,X):
        X = self.layer_1(X)
        X = self.batch_norm_1(X)
        X = self.act_1(X)
        X = self.dropout_1(X)
        X = self.layer_2(X)
        X = self.batch_norm_2(X)
        X = self.act_2(X)
        X = self.dropout_2(X)
        X = self.layer_3(X)
        X = self.batch_norm_3(X)
        X = self.act_3(X)
        X = self.dropout_3(X)
        out = self.layer_4(X)
        return out

In [24]:
#объявляем модель
model = MyNN(X_train_processed.shape[1], 1)

In [25]:
# задаем оптимизатор и метрику
loss_reg = nn.MSELoss()
opt = torch.optim.AdamW(model.parameters(), lr=1, weight_decay=0.01)

In [26]:
# задаем шедулер
lr_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(opt,  #оптимизатор
                                                          mode = 'min',  #'max' или 'min' - следим чтобы отслеживаемый параметр увеличивался()
                                                          factor = 0.1,  #коэфициэнт, на который будет умножен lr
                                                          patience = 10, #кол-во эпох без улучшения отслеживаемого пораметров
                                                          eps = 1e-8,
                                                          )

In [ ]:
#начинаем процесс обучения
EPOCHS = 500
train_loss = []
val_loss = []
lr_list = []
best_loss = None
best_model = 0
count = 0

for epoch in range(EPOCHS):
    model.train()
    train_loop = tqdm(train_loader,leave=False)
    running_train_loss = []
    for x,targets in train_loop:

        pred = model(x)
        loss = torch.sqrt(loss_reg(pred, targets))

        opt.zero_grad()
        loss.backward()

        opt.step()

        running_train_loss.append(loss.item())
        mean_train_loss = sum(running_train_loss)/len(running_train_loss)

        train_loop.set_description(f'Epoch[{epoch+1}/{EPOCHS}], train_loss = {mean_train_loss:.4f}')

    train_loss.append(mean_train_loss)

    model.eval()
    with torch.no_grad():
        running_val_loss = []
        for x, targets in val_loader:
            pred = model(x)
            loss = torch.sqrt(loss_reg(pred,targets))

            running_val_loss.append(loss.item())
            mean_val_loss = sum(running_val_loss)/len(running_val_loss)

        val_loss.append(mean_val_loss)

    lr_scheduler.step(mean_val_loss)

    lr = lr_scheduler._last_lr[0]
    lr_list.append(lr)
    print((f'Epoch [{epoch+1}/{EPOCHS}], train_loss = {mean_train_loss:.4f},  val_loss = {mean_val_loss:.4f}, lr = {lr:.4f}'))

    if best_loss is None:
      best_loss = mean_val_loss

    if mean_val_loss < best_loss:
      best_loss = mean_val_loss
      count = 0
      checkpoint = {
          'state_model': model.state_dict(),
          'state_opt' : opt.state_dict(),
          'state_lr_scheduler': lr_scheduler.state_dict(),
          'loss' : {
              'train_loss':train_loss,
              'val_loss': val_loss,
              'best_loss': best_loss,
          },
          'metric':{
              'train_loss' : train_loss,
              'val_loss' : val_loss,
          },
          'lr' : lr_list,
          'epoch' : {
              'EPOCHS' : EPOCHS,
              'save_epoch': epoch
          }
      }

      if best_model == 0:
        torch.save(model.state_dict(), f'best_nn_model/model_state_dict_epoch_{epoch+1}.pt')
        best_model = epoch+1

      else:
        os.remove(f'best_nn_model/model_state_dict_epoch_{best_model}.pt')
        torch.save(model.state_dict(), f'best_nn_model/model_state_dict_epoch_{epoch+1}.pt')
        best_model = epoch+1

      print(f'На эпохе - {epoch+1}, сохранена модель со значением функции потерь на валидации - {best_loss:.4f}', end='\n\n') 

    if count >= 150:
      print(f'\033[31Обучение остановлено на {epoch+1} эпохе.\033[0m')
      break
    count += 1

Epoch [1/500], train_loss = 3.4462,  val_loss = 1.1732, lr = 1.0000

Epoch [2/500], train_loss = 0.4164,  val_loss = 0.3034, lr = 1.0000
На эпохе - 2, сохранена модель со значением функции потерь на валидации - 0.3034

Epoch [3/500], train_loss = 0.3683,  val_loss = 0.6232, lr = 1.0000

Epoch [4/500], train_loss = 0.3704,  val_loss = 0.4597, lr = 1.0000

Epoch [5/500], train_loss = 0.3470,  val_loss = 0.4124, lr = 1.0000

Epoch [6/500], train_loss = 0.3370,  val_loss = 0.3056, lr = 1.0000

Epoch [7/500], train_loss = 0.3212,  val_loss = 0.2738, lr = 1.0000
На эпохе - 7, сохранена модель со значением функции потерь на валидации - 0.2738

Epoch [8/500], train_loss = 0.4099,  val_loss = 0.5783, lr = 1.0000

Epoch [9/500], train_loss = 0.4268,  val_loss = 0.5005, lr = 1.0000

Epoch [10/500], train_loss = 0.4290,  val_loss = 0.4558, lr = 1.0000

Epoch [11/500], train_loss = 0.3994,  val_loss = 39.8406, lr = 1.0000

Epoch [12/500], train_loss = 0.4153,  val_loss = 0.4549, lr = 1.0000

Epoch [13/500], train_loss = 0.4744,  val_loss = 48.9469, lr = 1.0000

Epoch [14/500], train_loss = 0.4061,  val_loss = 0.4580, lr = 1.0000

Epoch [15/500], train_loss = 0.3963,  val_loss = 0.4809, lr = 1.0000

Epoch [16/500], train_loss = 0.4039,  val_loss = 0.4681, lr = 1.0000

Epoch [17/500], train_loss = 0.3974,  val_loss = 0.4546, lr = 1.0000

Epoch [18/500], train_loss = 0.3942,  val_loss = 0.4606, lr = 0.1000

Epoch [19/500], train_loss = 0.3827,  val_loss = 0.4536, lr = 0.1000

Epoch [20/500], train_loss = 0.3865,  val_loss = 0.4538, lr = 0.1000

Epoch [21/500], train_loss = 0.3860,  val_loss = 0.4588, lr = 0.1000

Epoch [22/500], train_loss = 0.3846,  val_loss = 0.4543, lr = 0.1000

Epoch [23/500], train_loss = 0.3828,  val_loss = 0.4539, lr = 0.1000

Epoch [24/500], train_loss = 0.3849,  val_loss = 0.4543, lr = 0.1000

Epoch [25/500], train_loss = 0.3830,  val_loss = 0.4542, lr = 0.1000

Epoch [26/500], train_loss = 0.3813,  val_loss = 0.4565, lr = 0.1000

Epoch [27/500], train_loss = 0.3831,  val_loss = 0.4538, lr = 0.1000

Epoch [28/500], train_loss = 0.3839,  val_loss = 0.4536, lr = 0.1000

Epoch [29/500], train_loss = 0.3850,  val_loss = 0.4678, lr = 0.0100

Epoch [30/500], train_loss = 0.3881,  val_loss = 0.4490, lr = 0.0100

Epoch [31/500], train_loss = 0.3496,  val_loss = 0.3617, lr = 0.0100

Epoch [32/500], train_loss = 0.3029,  val_loss = 0.3311, lr = 0.0100

Epoch [33/500], train_loss = 0.3042,  val_loss = 0.3031, lr = 0.0100

Epoch [34/500], train_loss = 0.2873,  val_loss = 0.3076, lr = 0.0100

Epoch [35/500], train_loss = 0.2849,  val_loss = 0.2955, lr = 0.0100

Epoch [36/500], train_loss = 0.2504,  val_loss = 0.2831, lr = 0.0100

Epoch [37/500], train_loss = 0.2677,  val_loss = 0.2621, lr = 0.0100
На эпохе - 37, сохранена модель со значением функции потерь на валидации - 0.2621

Epoch [38/500], train_loss = 0.2651,  val_loss = 0.2819, lr = 0.0100

Epoch [39/500], train_loss = 0.2824,  val_loss = 0.2633, lr = 0.0100

Epoch [40/500], train_loss = 0.2554,  val_loss = 0.2679, lr = 0.0100

Epoch [41/500], train_loss = 0.2569,  val_loss = 0.2586, lr = 0.0100
На эпохе - 41, сохранена модель со значением функции потерь на валидации - 0.2586

Epoch [42/500], train_loss = 0.2608,  val_loss = 0.3097, lr = 0.0100

Epoch [43/500], train_loss = 0.2692,  val_loss = 0.2718, lr = 0.0100

Epoch [44/500], train_loss = 0.2666,  val_loss = 0.2615, lr = 0.0100

Epoch [45/500], train_loss = 0.2519,  val_loss = 0.2556, lr = 0.0100
На эпохе - 45, сохранена модель со значением функции потерь на валидации - 0.2556

Epoch [46/500], train_loss = 0.2644,  val_loss = 0.2645, lr = 0.0100

Epoch [47/500], train_loss = 0.2552,  val_loss = 0.2757, lr = 0.0100

Epoch [48/500], train_loss = 0.2629,  val_loss = 0.2589, lr = 0.0100

Epoch [49/500], train_loss = 0.2622,  val_loss = 0.2507, lr = 0.0100
На эпохе - 49, сохранена модель со значением функции потерь на валидации - 0.2507

Epoch [50/500], train_loss = 0.2577,  val_loss = 0.2794, lr = 0.0100

Epoch [51/500], train_loss = 0.2554,  val_loss = 0.2753, lr = 0.0100

Epoch [52/500], train_loss = 0.2624,  val_loss = 0.2776, lr = 0.0100

Epoch [53/500], train_loss = 0.2626,  val_loss = 0.2536, lr = 0.0100

Epoch [54/500], train_loss = 0.2559,  val_loss = 0.2442, lr = 0.0100
На эпохе - 54, сохранена модель со значением функции потерь на валидации - 0.2442

Epoch [55/500], train_loss = 0.2680,  val_loss = 0.2620, lr = 0.0100

Epoch [56/500], train_loss = 0.2468,  val_loss = 0.2534, lr = 0.0100

Epoch [57/500], train_loss = 0.2477,  val_loss = 0.2575, lr = 0.0100

Epoch [58/500], train_loss = 0.2674,  val_loss = 0.2853, lr = 0.0100

Epoch [59/500], train_loss = 0.2548,  val_loss = 0.2649, lr = 0.0100

Epoch [60/500], train_loss = 0.2520,  val_loss = 0.2520, lr = 0.0100

Epoch [61/500], train_loss = 0.2735,  val_loss = 0.2644, lr = 0.0100

Epoch [62/500], train_loss = 0.2441,  val_loss = 0.2710, lr = 0.0100

Epoch [63/500], train_loss = 0.2310,  val_loss = 0.2464, lr = 0.0100

Epoch [64/500], train_loss = 0.2481,  val_loss = 0.2716, lr = 0.0100

Epoch [65/500], train_loss = 0.2711,  val_loss = 0.2631, lr = 0.0010

Epoch [66/500], train_loss = 0.2575,  val_loss = 0.2705, lr = 0.0010

Epoch [67/500], train_loss = 0.2545,  val_loss = 0.2740, lr = 0.0010

Epoch [68/500], train_loss = 0.2556,  val_loss = 0.2737, lr = 0.0010

Epoch [69/500], train_loss = 0.2605,  val_loss = 0.2758, lr = 0.0010

Epoch [70/500], train_loss = 0.2496,  val_loss = 0.2815, lr = 0.0010

Epoch [71/500], train_loss = 0.2475,  val_loss = 0.2655, lr = 0.0010

Epoch [72/500], train_loss = 0.2500,  val_loss = 0.2722, lr = 0.0010

Epoch [73/500], train_loss = 0.2441,  val_loss = 0.2582, lr = 0.0010

Epoch [74/500], train_loss = 0.2717,  val_loss = 0.2662, lr = 0.0010

Epoch [75/500], train_loss = 0.2769,  val_loss = 0.2809, lr = 0.0010

Epoch [76/500], train_loss = 0.2489,  val_loss = 0.2662, lr = 0.0001

Epoch [77/500], train_loss = 0.2534,  val_loss = 0.2665, lr = 0.0001

Epoch [78/500], train_loss = 0.2607,  val_loss = 0.2714, lr = 0.0001

Epoch [79/500], train_loss = 0.2528,  val_loss = 0.2639, lr = 0.0001

Epoch [80/500], train_loss = 0.2447,  val_loss = 0.2749, lr = 0.0001

Epoch [81/500], train_loss = 0.2416,  val_loss = 0.2725, lr = 0.0001

Epoch [82/500], train_loss = 0.2641,  val_loss = 0.2731, lr = 0.0001

Epoch [83/500], train_loss = 0.2634,  val_loss = 0.2733, lr = 0.0001

Epoch [84/500], train_loss = 0.2481,  val_loss = 0.2672, lr = 0.0001

Epoch [85/500], train_loss = 0.2678,  val_loss = 0.2648, lr = 0.0001

Epoch [86/500], train_loss = 0.2528,  val_loss = 0.2661, lr = 0.0001

Epoch [87/500], train_loss = 0.2542,  val_loss = 0.2646, lr = 0.0000

Epoch [88/500], train_loss = 0.2485,  val_loss = 0.2689, lr = 0.0000

Epoch [89/500], train_loss = 0.2483,  val_loss = 0.2662, lr = 0.0000

Epoch [90/500], train_loss = 0.2412,  val_loss = 0.2809, lr = 0.0000

Epoch [91/500], train_loss = 0.2556,  val_loss = 0.2722, lr = 0.0000

Epoch [92/500], train_loss = 0.2580,  val_loss = 0.2673, lr = 0.0000

Epoch [93/500], train_loss = 0.2599,  val_loss = 0.2658, lr = 0.0000

Epoch [94/500], train_loss = 0.2543,  val_loss = 0.2681, lr = 0.0000

Epoch [95/500], train_loss = 0.2490,  val_loss = 0.2663, lr = 0.0000

Epoch [96/500], train_loss = 0.2433,  val_loss = 0.2705, lr = 0.0000

Epoch [97/500], train_loss = 0.2531,  val_loss = 0.2669, lr = 0.0000

Epoch [98/500], train_loss = 0.2429,  val_loss = 0.2692, lr = 0.0000

Epoch [99/500], train_loss = 0.2492,  val_loss = 0.2717, lr = 0.0000

Epoch [100/500], train_loss = 0.2572,  val_loss = 0.2650, lr = 0.0000

Epoch [101/500], train_loss = 0.2632,  val_loss = 0.2705, lr = 0.0000

Epoch [102/500], train_loss = 0.2543,  val_loss = 0.2699, lr = 0.0000

Epoch [103/500], train_loss = 0.2612,  val_loss = 0.2641, lr = 0.0000

Epoch [104/500], train_loss = 0.2462,  val_loss = 0.2653, lr = 0.0000

Epoch [105/500], train_loss = 0.2583,  val_loss = 0.2719, lr = 0.0000

Epoch [106/500], train_loss = 0.2608,  val_loss = 0.2733, lr = 0.0000

Epoch [107/500], train_loss = 0.2517,  val_loss = 0.2729, lr = 0.0000

Epoch [108/500], train_loss = 0.2585,  val_loss = 0.2743, lr = 0.0000

Epoch [109/500], train_loss = 0.2682,  val_loss = 0.2647, lr = 0.0000

Epoch [110/500], train_loss = 0.2450,  val_loss = 0.2748, lr = 0.0000

Epoch [111/500], train_loss = 0.2618,  val_loss = 0.2740, lr = 0.0000

Epoch [112/500], train_loss = 0.2522,  val_loss = 0.2679, lr = 0.0000

Epoch [113/500], train_loss = 0.2592,  val_loss = 0.2667, lr = 0.0000

Epoch [114/500], train_loss = 0.2479,  val_loss = 0.2650, lr = 0.0000

Epoch [115/500], train_loss = 0.2450,  val_loss = 0.2720, lr = 0.0000

Epoch [116/500], train_loss = 0.2319,  val_loss = 0.2730, lr = 0.0000

Epoch [117/500], train_loss = 0.2501,  val_loss = 0.2604, lr = 0.0000

Epoch [118/500], train_loss = 0.2642,  val_loss = 0.2668, lr = 0.0000

Epoch [119/500], train_loss = 0.2563,  val_loss = 0.2625, lr = 0.0000

Epoch [120/500], train_loss = 0.2623,  val_loss = 0.2537, lr = 0.0000

Epoch [121/500], train_loss = 0.2481,  val_loss = 0.2638, lr = 0.0000

Epoch [122/500], train_loss = 0.2619,  val_loss = 0.2679, lr = 0.0000

Epoch [123/500], train_loss = 0.2475,  val_loss = 0.2714, lr = 0.0000

Epoch [124/500], train_loss = 0.2553,  val_loss = 0.2628, lr = 0.0000

Epoch [125/500], train_loss = 0.2559,  val_loss = 0.2717, lr = 0.0000

Epoch [126/500], train_loss = 0.2378,  val_loss = 0.2737, lr = 0.0000

Epoch [127/500], train_loss = 0.2584,  val_loss = 0.2687, lr = 0.0000

Epoch [128/500], train_loss = 0.2518,  val_loss = 0.2651, lr = 0.0000

Epoch [129/500], train_loss = 0.2530,  val_loss = 0.2689, lr = 0.0000

Epoch [130/500], train_loss = 0.2397,  val_loss = 0.2746, lr = 0.0000

Epoch [131/500], train_loss = 0.2601,  val_loss = 0.2735, lr = 0.0000

Epoch [132/500], train_loss = 0.2497,  val_loss = 0.2705, lr = 0.0000

Epoch [133/500], train_loss = 0.2600,  val_loss = 0.2675, lr = 0.0000

Epoch [134/500], train_loss = 0.2634,  val_loss = 0.2739, lr = 0.0000

Epoch [135/500], train_loss = 0.2478,  val_loss = 0.2752, lr = 0.0000

Epoch [136/500], train_loss = 0.2481,  val_loss = 0.2613, lr = 0.0000

Epoch [137/500], train_loss = 0.2587,  val_loss = 0.2718, lr = 0.0000

Epoch [138/500], train_loss = 0.2542,  val_loss = 0.2690, lr = 0.0000

Epoch [139/500], train_loss = 0.2629,  val_loss = 0.2726, lr = 0.0000

Epoch [140/500], train_loss = 0.2449,  val_loss = 0.2734, lr = 0.0000

Epoch [141/500], train_loss = 0.2515,  val_loss = 0.2657, lr = 0.0000

Epoch [142/500], train_loss = 0.2581,  val_loss = 0.2684, lr = 0.0000

Epoch [143/500], train_loss = 0.2528,  val_loss = 0.2666, lr = 0.0000

Epoch [144/500], train_loss = 0.2663,  val_loss = 0.2675, lr = 0.0000

Epoch [145/500], train_loss = 0.2472,  val_loss = 0.2654, lr = 0.0000

Epoch [146/500], train_loss = 0.2504,  val_loss = 0.2688, lr = 0.0000

Epoch [147/500], train_loss = 0.2650,  val_loss = 0.2712, lr = 0.0000

Epoch [148/500], train_loss = 0.2707,  val_loss = 0.2763, lr = 0.0000

Epoch [149/500], train_loss = 0.2489,  val_loss = 0.2706, lr = 0.0000

Epoch [150/500], train_loss = 0.2690,  val_loss = 0.2694, lr = 0.0000

Epoch [151/500], train_loss = 0.2552,  val_loss = 0.2660, lr = 0.0000

Epoch [152/500], train_loss = 0.2419,  val_loss = 0.2673, lr = 0.0000

Epoch [153/500], train_loss = 0.2613,  val_loss = 0.2718, lr = 0.0000

Epoch [154/500], train_loss = 0.2524,  val_loss = 0.2711, lr = 0.0000

Epoch [155/500], train_loss = 0.2524,  val_loss = 0.2718, lr = 0.0000

Epoch [156/500], train_loss = 0.2468,  val_loss = 0.2652, lr = 0.0000

Epoch [157/500], train_loss = 0.2620,  val_loss = 0.2717, lr = 0.0000

Epoch [158/500], train_loss = 0.2522,  val_loss = 0.2649, lr = 0.0000

Epoch [159/500], train_loss = 0.2645,  val_loss = 0.2634, lr = 0.0000

Epoch [160/500], train_loss = 0.2490,  val_loss = 0.2648, lr = 0.0000

Epoch [161/500], train_loss = 0.2689,  val_loss = 0.2643, lr = 0.0000

Epoch [162/500], train_loss = 0.2504,  val_loss = 0.2732, lr = 0.0000

Epoch [163/500], train_loss = 0.2621,  val_loss = 0.2644, lr = 0.0000

Epoch [164/500], train_loss = 0.2410,  val_loss = 0.2699, lr = 0.0000

Epoch [165/500], train_loss = 0.2531,  val_loss = 0.2640, lr = 0.0000

Epoch [166/500], train_loss = 0.2582,  val_loss = 0.2650, lr = 0.0000

Epoch [167/500], train_loss = 0.2562,  val_loss = 0.2776, lr = 0.0000

Epoch [168/500], train_loss = 0.2464,  val_loss = 0.2669, lr = 0.0000

Epoch [169/500], train_loss = 0.2527,  val_loss = 0.2752, lr = 0.0000

Epoch [170/500], train_loss = 0.2518,  val_loss = 0.2750, lr = 0.0000

Epoch [171/500], train_loss = 0.2573,  val_loss = 0.2620, lr = 0.0000

Epoch [172/500], train_loss = 0.2571,  val_loss = 0.2675, lr = 0.0000

Epoch [173/500], train_loss = 0.2462,  val_loss = 0.2708, lr = 0.0000

Epoch [174/500], train_loss = 0.2501,  val_loss = 0.2735, lr = 0.0000

Epoch [175/500], train_loss = 0.2507,  val_loss = 0.2668, lr = 0.0000

Epoch [176/500], train_loss = 0.2466,  val_loss = 0.2726, lr = 0.0000

Epoch [177/500], train_loss = 0.2496,  val_loss = 0.2690, lr = 0.0000

Epoch [178/500], train_loss = 0.2705,  val_loss = 0.2700, lr = 0.0000

Epoch [179/500], train_loss = 0.2571,  val_loss = 0.2695, lr = 0.0000

Epoch [180/500], train_loss = 0.2506,  val_loss = 0.2773, lr = 0.0000

Epoch [181/500], train_loss = 0.2493,  val_loss = 0.2708, lr = 0.0000

Epoch [182/500], train_loss = 0.2647,  val_loss = 0.2757, lr = 0.0000

Epoch [183/500], train_loss = 0.2509,  val_loss = 0.2742, lr = 0.0000

Epoch [184/500], train_loss = 0.2538,  val_loss = 0.2715, lr = 0.0000

Epoch [185/500], train_loss = 0.2583,  val_loss = 0.2656, lr = 0.0000

Epoch [186/500], train_loss = 0.2492,  val_loss = 0.2690, lr = 0.0000

Epoch [187/500], train_loss = 0.2609,  val_loss = 0.2655, lr = 0.0000

Epoch [188/500], train_loss = 0.2503,  val_loss = 0.2631, lr = 0.0000

Epoch [189/500], train_loss = 0.2420,  val_loss = 0.2723, lr = 0.0000

Epoch [190/500], train_loss = 0.2507,  val_loss = 0.2749, lr = 0.0000

Epoch [191/500], train_loss = 0.2615,  val_loss = 0.2651, lr = 0.0000

Epoch [192/500], train_loss = 0.2572,  val_loss = 0.2642, lr = 0.0000

Epoch [193/500], train_loss = 0.2476,  val_loss = 0.2691, lr = 0.0000

Epoch [194/500], train_loss = 0.2471,  val_loss = 0.2704, lr = 0.0000

Epoch [195/500], train_loss = 0.2383,  val_loss = 0.2726, lr = 0.0000

Epoch [196/500], train_loss = 0.2431,  val_loss = 0.2699, lr = 0.0000

Epoch [197/500], train_loss = 0.2612,  val_loss = 0.2711, lr = 0.0000

Epoch [198/500], train_loss = 0.2501,  val_loss = 0.2688, lr = 0.0000

Epoch [199/500], train_loss = 0.2753,  val_loss = 0.2705, lr = 0.0000

Epoch [200/500], train_loss = 0.2624,  val_loss = 0.2745, lr = 0.0000

Epoch [201/500], train_loss = 0.2351,  val_loss = 0.2690, lr = 0.0000

Epoch [202/500], train_loss = 0.2539,  val_loss = 0.2712, lr = 0.0000

Epoch [203/500], train_loss = 0.2434,  val_loss = 0.2663, lr = 0.0000

Epoch [204/500], train_loss = 0.2383,  val_loss = 0.2767, lr = 0.0000
[31Обучение остановлено на 204 эпохе.

In [ ]:
# загружаем веса лучшей модели и начинаем процесс тестирования
model.load_state_dict(torch.load(f'best_nn_model/model_state_dict_epoch_{best_model}.pt'))

model.eval()
with torch.no_grad():
    running_test_loss = []
    for x, targets in test_loader:
        pred = model(x)
        loss = torch.sqrt(loss_reg(pred,targets))
        running_test_loss.append(loss.item())

    mean_test_loss = sum(running_test_loss)/len(running_test_loss)
    print(f'Финальный loss = {mean_test_loss:.4f}')

Финальный loss = 0.4210

In [ ]:
# 2. Загружаем тестовый набор данных 
test_data = pd.read_csv('data/test.csv')
test_ids = test_data['Id']

# 3. Предобработка тестовых данных
X_test_final = prepare_data(test_data)
X_test_processed_final = preprocessor.transform(X_test_final)

# Конвертируем в тензор
X_test_tensor_final = torch.tensor(X_test_processed_final, dtype=torch.float32)

print("Данные готовы к предсказанию.")

Данные готовы к предсказанию.

c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [4, 8, 11] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [ ]:
model.eval()
with torch.no_grad():
    # Получаем предсказания
    log_preds = model(X_test_tensor_final).numpy().flatten()

# Переводим из логарифмического масштаба обратно
final_preds = np.expm1(log_preds)

# Создаем DataFrame для отправки
submission = pd.DataFrame({
    'Id': test_ids,
    'SalePrice': final_preds
})

# Сохраняем в CSV
submission.to_csv('data/nn_submission/submission.csv', index=False)

print("Файл submission.csv успешно создан!")
display(submission.head(30))

Файл submission.csv успешно создан!

      Id      SalePrice
0   1461  131898.796875
1   1462  155031.093750
2   1463  165267.937500
3   1464  171356.281250
4   1465  169083.781250
5   1466  162941.546875
6   1467  164827.843750
7   1468  156904.187500
8   1469  171125.046875
9   1470  131898.796875
10  1471  169172.500000
11  1472  131898.796875
12  1473  131898.796875
13  1474  146913.328125
14  1475  131898.796875
15  1476  261828.953125
16  1477  206150.031250
17  1478  222042.140625
18  1479  216211.828125
19  1480  344402.406250
20  1481  246605.281250
21  1482  175391.140625
22  1483  158563.234375
23  1484  155946.015625
24  1485  168086.171875
25  1486  172726.937500
26  1487  251527.437500
27  1488  187042.812500
28  1489  170210.156250
29  1490  201031.656250