In [ ]:
import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder, TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
# from sklearn.feature_selection import VarianceThreshold
from sklearn.impute import SimpleImputer
from sklearn.base import clone

import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn as nn
import os
from tqdm import tqdm

from prepare_data import prepare_data

import random

In [255]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [256]:
data = pd.read_csv('data/train.csv')
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [257]:
y = np.log1p(data['SalePrice'])
X = prepare_data(data.drop('SalePrice',axis=1))

In [258]:
X = X[X['GrLivArea'] < 4500]
#синхронизируем данные
y = y[X.index]

In [259]:
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.1, random_state=SEED)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=(0.2/0.9), random_state=SEED)

In [260]:
numeric_colums = X_train.select_dtypes(include=['number']).columns
categorical_colums = X_train.select_dtypes(include=['object', 'string']).columns

In [261]:
low_card_cols = [
    col for col in categorical_colums
    if X_train[col].nunique() < 5
]

high_card_cols = [
    col for col in categorical_colums
    if X_train[col].nunique() >= 5
]

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    # ('variance_selector', VarianceThreshold(threshold=0.1))
])

categorical_imputer = SimpleImputer(strategy='constant', fill_value='missing')  


preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', Pipeline([
            ('imputer', categorical_imputer),
            ('encoder', OneHotEncoder(
            drop='first',
            handle_unknown='ignore',
            sparse_output=False
        ))
        ]), low_card_cols),

        ('target', Pipeline([
            ('imputer', categorical_imputer),
            ('target',  TargetEncoder(
            target_type='continuous',
            random_state=SEED
        ))]), high_card_cols),

        ('numeric', numeric_transformer, numeric_colums)
    ],
    verbose_feature_names_out=False
)

preprocessor

ColumnTransformer(transformers=[('onehot',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Street', 'Alley', 'LotShape', 'LandContour',
                                  'Utilities', 'LandSlope', 'MasVnrType',
                                  'ExterQual', 'ExterCond', 'Heating',
                                  'CentralAir', 'KitchenQua...
       'BsmtUnfSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'TotalSF'],
      dtype='str'))],
                  verbose_feature_names_out=False)

In [262]:
preview_preprocessor = clone(preprocessor)
preview_preprocessor.set_output(transform='pandas')

X_encoded_preview = preview_preprocessor.fit_transform(X, y)
X_encoded_preview.head()

,Street_Pave,Alley_Grvl,Alley_Pave,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,Utilities_NoSeWa,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,TotalSF
0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,-0.750831,0.225982,-0.359603,-0.11642,-0.270407,-0.063709,-0.087748,-1.601578,0.138375,0.011436
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.627328,-0.708304,-0.359603,-0.11642,-0.270407,-0.063709,-0.087748,-0.490155,-0.614427,-0.042838
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.750831,-0.065025,-0.359603,-0.11642,-0.270407,-0.063709,-0.087748,0.991743,0.138375,0.192351
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.750831,-0.172238,4.089589,-0.11642,-0.270407,-0.063709,-0.087748,-1.601578,-1.367230,-0.108743
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.781406,0.578253,-0.359603,-0.11642,-0.270407,-0.063709,-0.087748,2.103167,0.138375,1.015514

In [263]:
generator = torch.Generator().manual_seed(SEED)

# Применяем препроцессор
X_train_processed = preprocessor.fit_transform(X_train, y_train)
X_val_processed = preprocessor.transform(X_val)
X_test_processed = preprocessor.transform(X_test)

# Преобразуем данные в тензоры PyTorch
X_train_tensor = torch.tensor(X_train_processed, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1)

X_val_tensor = torch.tensor(X_val_processed, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32).unsqueeze(1)

X_test_tensor = torch.tensor(X_test_processed, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1)

# Создаем TensorDataset
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

# Создаем DataLoader'ы
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True, generator=generator)
val_loader = DataLoader(dataset=val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False)

c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [8, 9, 14, 15] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [264]:

class MyNN(nn.Module):
    def __init__(self, input, output):
        super().__init__()
        self.layer_1 = nn.Linear(input,128)
        self.batch_norm_1 = nn.BatchNorm1d(128)
        self.act_1 = nn.LeakyReLU()
        self.dropout_1 = nn.Dropout(0.2)
        self.layer_2 = nn.Linear(128,64)
        self.batch_norm_2 = nn.BatchNorm1d(64)
        self.act_2 = nn.LeakyReLU()
        self.dropout_2 = nn.Dropout(0.2)
        self.layer_3 = nn.Linear(64,32)
        self.batch_norm_3 = nn.BatchNorm1d(32)
        self.act_3 = nn.ReLU()
        self.dropout_3 = nn.Dropout(0.2)
        self.layer_4 = nn.Linear(32,output)

    def forward(self,X):
        X = self.layer_1(X)
        X = self.batch_norm_1(X)
        X = self.act_1(X)
        X = self.dropout_1(X)
        X = self.layer_2(X)
        X = self.batch_norm_2(X)
        X = self.act_2(X)
        X = self.dropout_2(X)
        X = self.layer_3(X)
        X = self.batch_norm_3(X)
        X = self.act_3(X)
        X = self.dropout_3(X)
        out = self.layer_4(X)
        return out

In [265]:
model = MyNN(X_train_processed.shape[1], 1)

In [266]:
loss_reg = nn.MSELoss()
opt = torch.optim.AdamW(model.parameters(), lr=0.01, weight_decay=0.01)

In [267]:
from torch.optim import lr_scheduler

lr_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(opt,  #оптимизатор
                                                          mode = 'min',  #'max' или 'min' - следим чтобы отслеживаемый параметр увеличивался()
                                                          factor = 0.1,  #коэфициэнт, на который будет умножен lr
                                                          patience = 10, #кол-во эпох без улучшения отслеживаемого пораметров
                                                          eps = 1e-8,
                                                          )

In [ ]:


EPOCHS = 500
train_loss = []
val_loss = []
lr_list = []
best_loss = None
best_model = 0
count = 0

for epoch in range(EPOCHS):
    model.train()
    train_loop = tqdm(train_loader,leave=False)
    running_train_loss = []
    for x,targets in train_loop:

        pred = model(x)
        loss = torch.sqrt(loss_reg(pred, targets))

        opt.zero_grad()
        loss.backward()

        opt.step()

        running_train_loss.append(loss.item())
        mean_train_loss = sum(running_train_loss)/len(running_train_loss)

        train_loop.set_description(f'Epoch[{epoch+1}/{EPOCHS}], train_loss = {mean_train_loss:.4f}')

    train_loss.append(mean_train_loss)

    model.eval()
    with torch.no_grad():
        running_val_loss = []
        for x, targets in val_loader:
            pred = model(x)
            loss = torch.sqrt(loss_reg(pred,targets))

            running_val_loss.append(loss.item())
            mean_val_loss = sum(running_val_loss)/len(running_val_loss)

        val_loss.append(mean_val_loss)

    lr_scheduler.step(mean_val_loss)

    lr = lr_scheduler._last_lr[0]
    lr_list.append(lr)
    print((f'Epoch [{epoch+1}/{EPOCHS}], train_loss = {mean_train_loss:.4f},  val_loss = {mean_val_loss:.4f}, lr = {lr:.4f}'))

    if best_loss is None:
      best_loss = mean_val_loss

    if mean_val_loss < best_loss:
      best_loss = mean_val_loss
      count = 0
      checkpoint = {
          'state_model': model.state_dict(),
          'state_opt' : opt.state_dict(),
          'state_lr_scheduler': lr_scheduler.state_dict(),
          'loss' : {
              'train_loss':train_loss,
              'val_loss': val_loss,
              'best_loss': best_loss,
          },
          'metric':{
              'train_loss' : train_loss,
              'val_loss' : val_loss,
          },
          'lr' : lr_list,
          'epoch' : {
              'EPOCHS' : EPOCHS,
              'save_epoch': epoch
          }
      }

      if best_model == 0:
        torch.save(model.state_dict(), f'best_model/model_state_dict_epoch_{epoch+1}.pt')
        best_model = epoch+1

      else:
        os.remove(f'best_model/model_state_dict_epoch_{best_model}.pt')
        torch.save(model.state_dict(), f'best_model/model_state_dict_epoch_{epoch+1}.pt')
        best_model = epoch+1

      print(f'На эпохе - {epoch+1}, сохранена модель со значением функции потерь на валидации - {best_loss:.4f}', end='\n\n') 

    if count >= 150:
      print(f'\033[31Обучение остановлено на {epoch+1} эпохе.\033[0m')
      break
    count += 1

  0%|          | 0/32 [00:00<?, ?it/s]

Epoch [1/500], train_loss = 8.9704,  val_loss = 2.8008, lr = 0.0100

Epoch [2/500], train_loss = 2.3945,  val_loss = 2.6125, lr = 0.0100
На эпохе - 2, сохранена модель со значением функции потерь на валидации - 2.6125

Epoch [3/500], train_loss = 1.8404,  val_loss = 1.0275, lr = 0.0100
На эпохе - 3, сохранена модель со значением функции потерь на валидации - 1.0275

Epoch [4/500], train_loss = 1.6725,  val_loss = 0.8676, lr = 0.0100
На эпохе - 4, сохранена модель со значением функции потерь на валидации - 0.8676

Epoch [5/500], train_loss = 1.5875,  val_loss = 0.8508, lr = 0.0100
На эпохе - 5, сохранена модель со значением функции потерь на валидации - 0.8508

Epoch [6/500], train_loss = 1.5970,  val_loss = 0.6404, lr = 0.0100
На эпохе - 6, сохранена модель со значением функции потерь на валидации - 0.6404

Epoch [7/500], train_loss = 1.5996,  val_loss = 0.6385, lr = 0.0100
На эпохе - 7, сохранена модель со значением функции потерь на валидации - 0.6385

Epoch [8/500], train_loss = 1.5418,  val_loss = 0.7771, lr = 0.0100

Epoch [9/500], train_loss = 1.4740,  val_loss = 0.8417, lr = 0.0100

Epoch [10/500], train_loss = 1.4247,  val_loss = 0.3805, lr = 0.0100
На эпохе - 10, сохранена модель со значением функции потерь на валидации - 0.3805

Epoch [11/500], train_loss = 1.3778,  val_loss = 0.6172, lr = 0.0100

Epoch [12/500], train_loss = 1.3324,  val_loss = 0.9538, lr = 0.0100

Epoch [13/500], train_loss = 1.3353,  val_loss = 0.3728, lr = 0.0100
На эпохе - 13, сохранена модель со значением функции потерь на валидации - 0.3728

Epoch [14/500], train_loss = 1.2897,  val_loss = 0.5105, lr = 0.0100

Epoch [15/500], train_loss = 1.2350,  val_loss = 0.3824, lr = 0.0100

Epoch [16/500], train_loss = 1.3011,  val_loss = 0.6719, lr = 0.0100

Epoch [17/500], train_loss = 1.2180,  val_loss = 0.5505, lr = 0.0100

Epoch [18/500], train_loss = 1.2339,  val_loss = 0.6925, lr = 0.0100

Epoch [19/500], train_loss = 1.1761,  val_loss = 0.3968, lr = 0.0100

Epoch [20/500], train_loss = 1.1608,  val_loss = 0.3223, lr = 0.0100
На эпохе - 20, сохранена модель со значением функции потерь на валидации - 0.3223

Epoch [21/500], train_loss = 1.1153,  val_loss = 0.4047, lr = 0.0100

Epoch [22/500], train_loss = 1.1168,  val_loss = 0.4786, lr = 0.0100

Epoch [23/500], train_loss = 1.1009,  val_loss = 0.3662, lr = 0.0100

Epoch [24/500], train_loss = 1.0891,  val_loss = 0.4562, lr = 0.0100

Epoch [25/500], train_loss = 1.0477,  val_loss = 0.5774, lr = 0.0100

Epoch [26/500], train_loss = 1.0461,  val_loss = 0.4491, lr = 0.0100

Epoch [27/500], train_loss = 1.0736,  val_loss = 0.5679, lr = 0.0100

Epoch [28/500], train_loss = 1.0352,  val_loss = 0.3431, lr = 0.0100

Epoch [29/500], train_loss = 0.9881,  val_loss = 0.3076, lr = 0.0100
На эпохе - 29, сохранена модель со значением функции потерь на валидации - 0.3076

Epoch [30/500], train_loss = 0.9695,  val_loss = 0.3062, lr = 0.0100
На эпохе - 30, сохранена модель со значением функции потерь на валидации - 0.3062

Epoch [31/500], train_loss = 0.9650,  val_loss = 0.3852, lr = 0.0100

Epoch [32/500], train_loss = 0.9371,  val_loss = 0.3602, lr = 0.0100

Epoch [33/500], train_loss = 0.9446,  val_loss = 0.2877, lr = 0.0100
На эпохе - 33, сохранена модель со значением функции потерь на валидации - 0.2877

Epoch [34/500], train_loss = 0.8899,  val_loss = 0.3508, lr = 0.0100

Epoch [35/500], train_loss = 0.9096,  val_loss = 0.2928, lr = 0.0100

Epoch [36/500], train_loss = 0.8986,  val_loss = 0.2427, lr = 0.0100

На эпохе - 36, сохранена модель со значением функции потерь на валидации - 0.2427

Epoch [37/500], train_loss = 0.8588,  val_loss = 0.2140, lr = 0.0100
На эпохе - 37, сохранена модель со значением функции потерь на валидации - 0.2140

Epoch [38/500], train_loss = 0.8353,  val_loss = 0.4525, lr = 0.0100

Epoch [39/500], train_loss = 0.8165,  val_loss = 0.2713, lr = 0.0100

Epoch [40/500], train_loss = 0.8112,  val_loss = 0.3735, lr = 0.0100

Epoch [41/500], train_loss = 0.7986,  val_loss = 0.2052, lr = 0.0100
На эпохе - 41, сохранена модель со значением функции потерь на валидации - 0.2052

Epoch [42/500], train_loss = 0.7809,  val_loss = 0.1907, lr = 0.0100
На эпохе - 42, сохранена модель со значением функции потерь на валидации - 0.1907

Epoch [43/500], train_loss = 0.7693,  val_loss = 0.2460, lr = 0.0100

Epoch [44/500], train_loss = 0.7494,  val_loss = 0.2307, lr = 0.0100

Epoch [45/500], train_loss = 0.7370,  val_loss = 0.1932, lr = 0.0100

Epoch [46/500], train_loss = 0.7722,  val_loss = 0.2300, lr = 0.0100

Epoch [47/500], train_loss = 0.7188,  val_loss = 0.2216, lr = 0.0100

Epoch [48/500], train_loss = 0.6988,  val_loss = 0.2101, lr = 0.0100

Epoch [49/500], train_loss = 0.6899,  val_loss = 0.2223, lr = 0.0100

Epoch [50/500], train_loss = 0.7125,  val_loss = 0.1888, lr = 0.0100
На эпохе - 50, сохранена модель со значением функции потерь на валидации - 0.1888

Epoch [51/500], train_loss = 0.6734,  val_loss = 0.2480, lr = 0.0100

Epoch [52/500], train_loss = 0.6778,  val_loss = 0.2143, lr = 0.0100

Epoch [53/500], train_loss = 0.6726,  val_loss = 0.1785, lr = 0.0100
На эпохе - 53, сохранена модель со значением функции потерь на валидации - 0.1785

Epoch [54/500], train_loss = 0.6425,  val_loss = 0.1884, lr = 0.0100

Epoch [55/500], train_loss = 0.6302,  val_loss = 0.2171, lr = 0.0100

Epoch [56/500], train_loss = 0.6385,  val_loss = 0.3667, lr = 0.0100

Epoch [57/500], train_loss = 0.6187,  val_loss = 0.1961, lr = 0.0100

Epoch [58/500], train_loss = 0.6040,  val_loss = 0.2262, lr = 0.0100

Epoch [59/500], train_loss = 0.5958,  val_loss = 0.1905, lr = 0.0100

Epoch [60/500], train_loss = 0.5661,  val_loss = 0.1946, lr = 0.0100

Epoch [61/500], train_loss = 0.5636,  val_loss = 0.2284, lr = 0.0100

Epoch [62/500], train_loss = 0.5739,  val_loss = 0.2103, lr = 0.0100

Epoch [63/500], train_loss = 0.5494,  val_loss = 0.2846, lr = 0.0100

Epoch [64/500], train_loss = 0.5493,  val_loss = 0.2040, lr = 0.0010

Epoch [65/500], train_loss = 0.5192,  val_loss = 0.1850, lr = 0.0010

Epoch [66/500], train_loss = 0.5353,  val_loss = 0.1601, lr = 0.0010
На эпохе - 66, сохранена модель со значением функции потерь на валидации - 0.1601

Epoch [67/500], train_loss = 0.5304,  val_loss = 0.1648, lr = 0.0010

Epoch [68/500], train_loss = 0.5360,  val_loss = 0.1666, lr = 0.0010

Epoch [69/500], train_loss = 0.5402,  val_loss = 0.1634, lr = 0.0010

Epoch [70/500], train_loss = 0.5403,  val_loss = 0.1903, lr = 0.0010

Epoch [71/500], train_loss = 0.5520,  val_loss = 0.1734, lr = 0.0010

Epoch [72/500], train_loss = 0.5587,  val_loss = 0.1602, lr = 0.0010

Epoch [73/500], train_loss = 0.5117,  val_loss = 0.1680, lr = 0.0010

Epoch [74/500], train_loss = 0.5408,  val_loss = 0.1701, lr = 0.0010

Epoch [75/500], train_loss = 0.5384,  val_loss = 0.1724, lr = 0.0010

Epoch [76/500], train_loss = 0.5221,  val_loss = 0.1616, lr = 0.0010

Epoch [77/500], train_loss = 0.5124,  val_loss = 0.1670, lr = 0.0001

Epoch [78/500], train_loss = 0.5239,  val_loss = 0.1715, lr = 0.0001

Epoch [79/500], train_loss = 0.5160,  val_loss = 0.1658, lr = 0.0001

Epoch [80/500], train_loss = 0.5250,  val_loss = 0.1593, lr = 0.0001
На эпохе - 80, сохранена модель со значением функции потерь на валидации - 0.1593

Epoch [81/500], train_loss = 0.5303,  val_loss = 0.1621, lr = 0.0001

Epoch [82/500], train_loss = 0.5410,  val_loss = 0.1622, lr = 0.0001

Epoch [83/500], train_loss = 0.5181,  val_loss = 0.1686, lr = 0.0001

Epoch [84/500], train_loss = 0.5057,  val_loss = 0.1701, lr = 0.0001

Epoch [85/500], train_loss = 0.5061,  val_loss = 0.1771, lr = 0.0001

Epoch [86/500], train_loss = 0.5325,  val_loss = 0.1680, lr = 0.0001

Epoch [87/500], train_loss = 0.5011,  val_loss = 0.1644, lr = 0.0001

Epoch [88/500], train_loss = 0.5116,  val_loss = 0.1708, lr = 0.0001

Epoch [89/500], train_loss = 0.4920,  val_loss = 0.1650, lr = 0.0001

Epoch [90/500], train_loss = 0.5107,  val_loss = 0.1570, lr = 0.0001
На эпохе - 90, сохранена модель со значением функции потерь на валидации - 0.1570

Epoch [91/500], train_loss = 0.4994,  val_loss = 0.1651, lr = 0.0001

Epoch [92/500], train_loss = 0.5467,  val_loss = 0.1546, lr = 0.0001
На эпохе - 92, сохранена модель со значением функции потерь на валидации - 0.1546

Epoch [93/500], train_loss = 0.5287,  val_loss = 0.1564, lr = 0.0001

Epoch [94/500], train_loss = 0.5138,  val_loss = 0.1547, lr = 0.0001

Epoch [95/500], train_loss = 0.5289,  val_loss = 0.1582, lr = 0.0001

Epoch [96/500], train_loss = 0.5258,  val_loss = 0.1577, lr = 0.0001

Epoch [97/500], train_loss = 0.5431,  val_loss = 0.1591, lr = 0.0001

Epoch [98/500], train_loss = 0.5308,  val_loss = 0.1664, lr = 0.0001

Epoch [99/500], train_loss = 0.5264,  val_loss = 0.1631, lr = 0.0001

Epoch [100/500], train_loss = 0.5124,  val_loss = 0.1640, lr = 0.0001

Epoch [101/500], train_loss = 0.5234,  val_loss = 0.1628, lr = 0.0001

Epoch [102/500], train_loss = 0.5202,  val_loss = 0.1665, lr = 0.0001

Epoch [103/500], train_loss = 0.4865,  val_loss = 0.1593, lr = 0.0000

Epoch [104/500], train_loss = 0.5161,  val_loss = 0.1603, lr = 0.0000

Epoch [105/500], train_loss = 0.5303,  val_loss = 0.1590, lr = 0.0000

Epoch [106/500], train_loss = 0.5238,  val_loss = 0.1577, lr = 0.0000

Epoch [107/500], train_loss = 0.5098,  val_loss = 0.1623, lr = 0.0000

Epoch [108/500], train_loss = 0.5233,  val_loss = 0.1578, lr = 0.0000

Epoch [109/500], train_loss = 0.5223,  val_loss = 0.1629, lr = 0.0000

Epoch [110/500], train_loss = 0.5228,  val_loss = 0.1657, lr = 0.0000

Epoch [111/500], train_loss = 0.5375,  val_loss = 0.1576, lr = 0.0000

Epoch [112/500], train_loss = 0.5219,  val_loss = 0.1654, lr = 0.0000

Epoch [113/500], train_loss = 0.5114,  val_loss = 0.1601, lr = 0.0000

Epoch [114/500], train_loss = 0.5180,  val_loss = 0.1687, lr = 0.0000

Epoch [115/500], train_loss = 0.5150,  val_loss = 0.1626, lr = 0.0000

Epoch [116/500], train_loss = 0.5346,  val_loss = 0.1571, lr = 0.0000

Epoch [117/500], train_loss = 0.5118,  val_loss = 0.1595, lr = 0.0000

Epoch [118/500], train_loss = 0.5054,  val_loss = 0.1577, lr = 0.0000

Epoch [119/500], train_loss = 0.5063,  val_loss = 0.1569, lr = 0.0000

Epoch [120/500], train_loss = 0.5132,  val_loss = 0.1586, lr = 0.0000

Epoch [121/500], train_loss = 0.5140,  val_loss = 0.1617, lr = 0.0000

Epoch [122/500], train_loss = 0.5068,  val_loss = 0.1565, lr = 0.0000

Epoch [123/500], train_loss = 0.5188,  val_loss = 0.1612, lr = 0.0000

Epoch [124/500], train_loss = 0.5131,  val_loss = 0.1599, lr = 0.0000

Epoch [125/500], train_loss = 0.5341,  val_loss = 0.1627, lr = 0.0000

Epoch [126/500], train_loss = 0.5076,  val_loss = 0.1679, lr = 0.0000

Epoch [127/500], train_loss = 0.5237,  val_loss = 0.1572, lr = 0.0000

Epoch [128/500], train_loss = 0.5150,  val_loss = 0.1594, lr = 0.0000

Epoch [129/500], train_loss = 0.5169,  val_loss = 0.1652, lr = 0.0000

Epoch [130/500], train_loss = 0.5361,  val_loss = 0.1581, lr = 0.0000

Epoch [131/500], train_loss = 0.5105,  val_loss = 0.1660, lr = 0.0000

Epoch [132/500], train_loss = 0.5294,  val_loss = 0.1611, lr = 0.0000

Epoch [133/500], train_loss = 0.4980,  val_loss = 0.1554, lr = 0.0000

Epoch [134/500], train_loss = 0.5307,  val_loss = 0.1613, lr = 0.0000

Epoch [135/500], train_loss = 0.5190,  val_loss = 0.1612, lr = 0.0000

Epoch [136/500], train_loss = 0.5161,  val_loss = 0.1640, lr = 0.0000

Epoch [137/500], train_loss = 0.5204,  val_loss = 0.1590, lr = 0.0000

Epoch [138/500], train_loss = 0.5053,  val_loss = 0.1629, lr = 0.0000

Epoch [139/500], train_loss = 0.5128,  val_loss = 0.1541, lr = 0.0000
На эпохе - 139, сохранена модель со значением функции потерь на валидации - 0.1541

Epoch [140/500], train_loss = 0.5148,  val_loss = 0.1583, lr = 0.0000

Epoch [141/500], train_loss = 0.5127,  val_loss = 0.1590, lr = 0.0000

Epoch [142/500], train_loss = 0.5140,  val_loss = 0.1627, lr = 0.0000

Epoch [143/500], train_loss = 0.5133,  val_loss = 0.1619, lr = 0.0000

Epoch [144/500], train_loss = 0.5259,  val_loss = 0.1648, lr = 0.0000

Epoch [145/500], train_loss = 0.5282,  val_loss = 0.1624, lr = 0.0000

Epoch [146/500], train_loss = 0.5317,  val_loss = 0.1730, lr = 0.0000

Epoch [147/500], train_loss = 0.5195,  val_loss = 0.1682, lr = 0.0000

Epoch [148/500], train_loss = 0.5091,  val_loss = 0.1639, lr = 0.0000

Epoch [149/500], train_loss = 0.5257,  val_loss = 0.1551, lr = 0.0000

Epoch [150/500], train_loss = 0.5330,  val_loss = 0.1589, lr = 0.0000

Epoch [151/500], train_loss = 0.5230,  val_loss = 0.1546, lr = 0.0000

Epoch [152/500], train_loss = 0.5198,  val_loss = 0.1696, lr = 0.0000

Epoch [153/500], train_loss = 0.5089,  val_loss = 0.1610, lr = 0.0000

Epoch [154/500], train_loss = 0.5103,  val_loss = 0.1657, lr = 0.0000

Epoch [155/500], train_loss = 0.5267,  val_loss = 0.1579, lr = 0.0000

Epoch [156/500], train_loss = 0.5010,  val_loss = 0.1589, lr = 0.0000

Epoch [157/500], train_loss = 0.5298,  val_loss = 0.1653, lr = 0.0000

Epoch [158/500], train_loss = 0.5118,  val_loss = 0.1624, lr = 0.0000

Epoch [159/500], train_loss = 0.5041,  val_loss = 0.1580, lr = 0.0000

Epoch [160/500], train_loss = 0.5109,  val_loss = 0.1629, lr = 0.0000

Epoch [161/500], train_loss = 0.5103,  val_loss = 0.1615, lr = 0.0000

Epoch [162/500], train_loss = 0.5463,  val_loss = 0.1600, lr = 0.0000

Epoch [163/500], train_loss = 0.5349,  val_loss = 0.1599, lr = 0.0000

Epoch [164/500], train_loss = 0.5157,  val_loss = 0.1581, lr = 0.0000

Epoch [165/500], train_loss = 0.5346,  val_loss = 0.1556, lr = 0.0000

Epoch [166/500], train_loss = 0.5226,  val_loss = 0.1580, lr = 0.0000

Epoch [167/500], train_loss = 0.5242,  val_loss = 0.1580, lr = 0.0000

Epoch [168/500], train_loss = 0.5477,  val_loss = 0.1542, lr = 0.0000

Epoch [169/500], train_loss = 0.5342,  val_loss = 0.1611, lr = 0.0000

Epoch [170/500], train_loss = 0.5165,  val_loss = 0.1573, lr = 0.0000

Epoch [171/500], train_loss = 0.5097,  val_loss = 0.1660, lr = 0.0000

Epoch [172/500], train_loss = 0.5158,  val_loss = 0.1634, lr = 0.0000

Epoch [173/500], train_loss = 0.5338,  val_loss = 0.1626, lr = 0.0000

Epoch [174/500], train_loss = 0.5194,  val_loss = 0.1588, lr = 0.0000

Epoch [175/500], train_loss = 0.5362,  val_loss = 0.1619, lr = 0.0000

Epoch [176/500], train_loss = 0.5182,  val_loss = 0.1625, lr = 0.0000

Epoch [177/500], train_loss = 0.4879,  val_loss = 0.1632, lr = 0.0000

Epoch [178/500], train_loss = 0.5125,  val_loss = 0.1571, lr = 0.0000

Epoch [179/500], train_loss = 0.5055,  val_loss = 0.1657, lr = 0.0000

Epoch [180/500], train_loss = 0.5156,  val_loss = 0.1658, lr = 0.0000

Epoch [181/500], train_loss = 0.5267,  val_loss = 0.1669, lr = 0.0000

Epoch [182/500], train_loss = 0.5262,  val_loss = 0.1610, lr = 0.0000

Epoch [183/500], train_loss = 0.5177,  val_loss = 0.1655, lr = 0.0000

Epoch [184/500], train_loss = 0.5324,  val_loss = 0.1559, lr = 0.0000

Epoch [185/500], train_loss = 0.5523,  val_loss = 0.1592, lr = 0.0000

Epoch [186/500], train_loss = 0.5239,  val_loss = 0.1690, lr = 0.0000

Epoch [187/500], train_loss = 0.5260,  val_loss = 0.1623, lr = 0.0000

Epoch [188/500], train_loss = 0.5213,  val_loss = 0.1595, lr = 0.0000

Epoch [189/500], train_loss = 0.4913,  val_loss = 0.1692, lr = 0.0000

Epoch [190/500], train_loss = 0.5227,  val_loss = 0.1658, lr = 0.0000

Epoch [191/500], train_loss = 0.5216,  val_loss = 0.1622, lr = 0.0000

Epoch [192/500], train_loss = 0.5384,  val_loss = 0.1584, lr = 0.0000

Epoch [193/500], train_loss = 0.5146,  val_loss = 0.1560, lr = 0.0000

Epoch [194/500], train_loss = 0.5234,  val_loss = 0.1674, lr = 0.0000

Epoch [195/500], train_loss = 0.5034,  val_loss = 0.1742, lr = 0.0000

Epoch [196/500], train_loss = 0.5101,  val_loss = 0.1616, lr = 0.0000

Epoch [197/500], train_loss = 0.5219,  val_loss = 0.1568, lr = 0.0000

Epoch [198/500], train_loss = 0.5192,  val_loss = 0.1580, lr = 0.0000

Epoch [199/500], train_loss = 0.5154,  val_loss = 0.1596, lr = 0.0000

Epoch [200/500], train_loss = 0.5381,  val_loss = 0.1577, lr = 0.0000

Epoch [201/500], train_loss = 0.5170,  val_loss = 0.1567, lr = 0.0000

Epoch [202/500], train_loss = 0.5222,  val_loss = 0.1565, lr = 0.0000

Epoch [203/500], train_loss = 0.5293,  val_loss = 0.1698, lr = 0.0000

Epoch [204/500], train_loss = 0.5168,  val_loss = 0.1571, lr = 0.0000

Epoch [205/500], train_loss = 0.5158,  val_loss = 0.1586, lr = 0.0000

Epoch [206/500], train_loss = 0.5170,  val_loss = 0.1618, lr = 0.0000

Epoch [207/500], train_loss = 0.5079,  val_loss = 0.1661, lr = 0.0000

Epoch [208/500], train_loss = 0.5022,  val_loss = 0.1580, lr = 0.0000

Epoch [209/500], train_loss = 0.5092,  val_loss = 0.1613, lr = 0.0000

Epoch [210/500], train_loss = 0.5069,  val_loss = 0.1630, lr = 0.0000

Epoch [211/500], train_loss = 0.5252,  val_loss = 0.1686, lr = 0.0000

Epoch [212/500], train_loss = 0.5335,  val_loss = 0.1579, lr = 0.0000

Epoch [213/500], train_loss = 0.5254,  val_loss = 0.1642, lr = 0.0000

Epoch [214/500], train_loss = 0.5167,  val_loss = 0.1616, lr = 0.0000

Epoch [215/500], train_loss = 0.5421,  val_loss = 0.1558, lr = 0.0000

Epoch [216/500], train_loss = 0.5115,  val_loss = 0.1646, lr = 0.0000

Epoch [217/500], train_loss = 0.5130,  val_loss = 0.1603, lr = 0.0000

Epoch [218/500], train_loss = 0.5112,  val_loss = 0.1575, lr = 0.0000

Epoch [219/500], train_loss = 0.4836,  val_loss = 0.1652, lr = 0.0000

Epoch [220/500], train_loss = 0.5079,  val_loss = 0.1640, lr = 0.0000

Epoch [221/500], train_loss = 0.5189,  val_loss = 0.1570, lr = 0.0000

Epoch [222/500], train_loss = 0.5090,  val_loss = 0.1648, lr = 0.0000

Epoch [223/500], train_loss = 0.5342,  val_loss = 0.1645, lr = 0.0000

Epoch [224/500], train_loss = 0.5141,  val_loss = 0.1622, lr = 0.0000

Epoch [225/500], train_loss = 0.5127,  val_loss = 0.1599, lr = 0.0000

Epoch [226/500], train_loss = 0.5087,  val_loss = 0.1611, lr = 0.0000

Epoch [227/500], train_loss = 0.5044,  val_loss = 0.1624, lr = 0.0000

Epoch [228/500], train_loss = 0.5120,  val_loss = 0.1616, lr = 0.0000

Epoch [229/500], train_loss = 0.5140,  val_loss = 0.1591, lr = 0.0000

Epoch [230/500], train_loss = 0.5251,  val_loss = 0.1645, lr = 0.0000

Epoch [231/500], train_loss = 0.5277,  val_loss = 0.1598, lr = 0.0000

Epoch [232/500], train_loss = 0.5406,  val_loss = 0.1619, lr = 0.0000

Epoch [233/500], train_loss = 0.5358,  val_loss = 0.1577, lr = 0.0000

Epoch [234/500], train_loss = 0.5052,  val_loss = 0.1645, lr = 0.0000

Epoch [235/500], train_loss = 0.5110,  val_loss = 0.1606, lr = 0.0000

Epoch [236/500], train_loss = 0.5334,  val_loss = 0.1634, lr = 0.0000

Epoch [237/500], train_loss = 0.5355,  val_loss = 0.1632, lr = 0.0000

Epoch [238/500], train_loss = 0.5122,  val_loss = 0.1584, lr = 0.0000

Epoch [239/500], train_loss = 0.5133,  val_loss = 0.1664, lr = 0.0000

Epoch [240/500], train_loss = 0.5254,  val_loss = 0.1662, lr = 0.0000

Epoch [241/500], train_loss = 0.5173,  val_loss = 0.1573, lr = 0.0000

Epoch [242/500], train_loss = 0.5273,  val_loss = 0.1609, lr = 0.0000

Epoch [243/500], train_loss = 0.5281,  val_loss = 0.1592, lr = 0.0000

Epoch [244/500], train_loss = 0.5147,  val_loss = 0.1569, lr = 0.0000

Epoch [245/500], train_loss = 0.5245,  val_loss = 0.1625, lr = 0.0000

Epoch [246/500], train_loss = 0.5163,  val_loss = 0.1581, lr = 0.0000

Epoch [247/500], train_loss = 0.5071,  val_loss = 0.1595, lr = 0.0000

Epoch [248/500], train_loss = 0.5300,  val_loss = 0.1585, lr = 0.0000

Epoch [249/500], train_loss = 0.5266,  val_loss = 0.1583, lr = 0.0000

Epoch [250/500], train_loss = 0.5370,  val_loss = 0.1570, lr = 0.0000

Epoch [251/500], train_loss = 0.5403,  val_loss = 0.1604, lr = 0.0000

Epoch [252/500], train_loss = 0.5284,  val_loss = 0.1579, lr = 0.0000

Epoch [253/500], train_loss = 0.5117,  val_loss = 0.1629, lr = 0.0000

Epoch [254/500], train_loss = 0.5117,  val_loss = 0.1612, lr = 0.0000

Epoch [255/500], train_loss = 0.5230,  val_loss = 0.1597, lr = 0.0000

Epoch [256/500], train_loss = 0.5025,  val_loss = 0.1615, lr = 0.0000

Epoch [257/500], train_loss = 0.5264,  val_loss = 0.1633, lr = 0.0000

Epoch [258/500], train_loss = 0.5233,  val_loss = 0.1628, lr = 0.0000

Epoch [259/500], train_loss = 0.5235,  val_loss = 0.1574, lr = 0.0000

Epoch [260/500], train_loss = 0.5137,  val_loss = 0.1631, lr = 0.0000

Epoch [261/500], train_loss = 0.5201,  val_loss = 0.1650, lr = 0.0000

Epoch [262/500], train_loss = 0.5025,  val_loss = 0.1567, lr = 0.0000

Epoch [263/500], train_loss = 0.5216,  val_loss = 0.1641, lr = 0.0000

Epoch [264/500], train_loss = 0.5387,  val_loss = 0.1655, lr = 0.0000

Epoch [265/500], train_loss = 0.5099,  val_loss = 0.1606, lr = 0.0000

Epoch [266/500], train_loss = 0.5102,  val_loss = 0.1625, lr = 0.0000

Epoch [267/500], train_loss = 0.5322,  val_loss = 0.1664, lr = 0.0000

Epoch [268/500], train_loss = 0.5187,  val_loss = 0.1709, lr = 0.0000

Epoch [269/500], train_loss = 0.5243,  val_loss = 0.1593, lr = 0.0000

Epoch [270/500], train_loss = 0.5065,  val_loss = 0.1613, lr = 0.0000

Epoch [271/500], train_loss = 0.5287,  val_loss = 0.1564, lr = 0.0000

Epoch [272/500], train_loss = 0.5268,  val_loss = 0.1616, lr = 0.0000

Epoch [273/500], train_loss = 0.5114,  val_loss = 0.1633, lr = 0.0000

Epoch [274/500], train_loss = 0.5259,  val_loss = 0.1570, lr = 0.0000

Epoch [275/500], train_loss = 0.5177,  val_loss = 0.1592, lr = 0.0000

Epoch [276/500], train_loss = 0.5243,  val_loss = 0.1629, lr = 0.0000

Epoch [277/500], train_loss = 0.5167,  val_loss = 0.1562, lr = 0.0000

Epoch [278/500], train_loss = 0.5161,  val_loss = 0.1683, lr = 0.0000

Epoch [279/500], train_loss = 0.5123,  val_loss = 0.1617, lr = 0.0000

Epoch [280/500], train_loss = 0.5253,  val_loss = 0.1677, lr = 0.0000

Epoch [281/500], train_loss = 0.5300,  val_loss = 0.1635, lr = 0.0000

Epoch [282/500], train_loss = 0.5186,  val_loss = 0.1591, lr = 0.0000

Epoch [283/500], train_loss = 0.5288,  val_loss = 0.1581, lr = 0.0000

Epoch [284/500], train_loss = 0.5253,  val_loss = 0.1622, lr = 0.0000

Epoch [285/500], train_loss = 0.5141,  val_loss = 0.1573, lr = 0.0000

Epoch [286/500], train_loss = 0.5033,  val_loss = 0.1595, lr = 0.0000

Epoch [287/500], train_loss = 0.5301,  val_loss = 0.1557, lr = 0.0000

Epoch [288/500], train_loss = 0.5393,  val_loss = 0.1772, lr = 0.0000

Epoch [289/500], train_loss = 0.5336,  val_loss = 0.1670, lr = 0.0000
[31Обучение остановлено на 289 эпохе.

In [269]:
model.load_state_dict(torch.load(f'best_model/model_state_dict_epoch_{best_model}.pt'))

model.eval()
with torch.no_grad():
    running_test_loss = []
    for x, targets in test_loader:
        pred = model(x)
        loss = torch.sqrt(loss_reg(pred,targets))
        running_test_loss.append(loss.item())

    mean_test_loss = sum(running_test_loss)/len(running_test_loss)
    

    print(f'Финальный loss = {mean_test_loss:.4f}')

Финальный loss = 0.1319

In [270]:
# 1. Загружаем веса лучшей модели (используем best_model из вашего цикла)
model.load_state_dict(torch.load(f'best_model/model_state_dict_epoch_{best_model}.pt'))
model.eval()

# 2. Загружаем тестовый набор данных Kaggle
test_data = pd.read_csv('data/test.csv')
test_ids = test_data['Id']

# 3. Предобработка тестовых данных
# Используем ту же функцию prepare_data и тот же preprocessor (только transform!)
X_test_final = prepare_data(test_data)
X_test_processed_final = preprocessor.transform(X_test_final)

# Конвертируем в тензор
X_test_tensor_final = torch.tensor(X_test_processed_final, dtype=torch.float32)

print("Данные готовы к предсказанию.")

c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [4, 8, 11] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

Данные готовы к предсказанию.

In [271]:
with torch.no_grad():
    # Получаем предсказания
    log_preds = model(X_test_tensor_final).numpy().flatten()

# Переводим из логарифмического масштаба обратно
final_preds = np.expm1(log_preds)

# Создаем DataFrame для отправки
submission = pd.DataFrame({
    'Id': test_ids,
    'SalePrice': final_preds
})

# Сохраняем в CSV
submission.to_csv('data/nn/submission.csv', index=False)

print("Файл submission.csv успешно создан!")
display(submission.head())

Файл submission.csv успешно создан!

     Id      SalePrice
0  1461  118698.796875
1  1462  204890.937500
2  1463  167214.484375
3  1464  178270.421875
4  1465  178570.578125