In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.base import clone

import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn as nn

import os
from tqdm import tqdm
import random

from feature_engineering import engineer_features
from preprocessing import create_preprocessor

In [2]:
#объявляем random.seed

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [3]:
#загружаем тренировочные данные
data = pd.read_csv('data/train.csv')
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [ ]:
y = np.log1p(data['SalePrice'])
X = engineer_features(data.drop('SalePrice',axis=1))

In [5]:
#удаляем выбросы
X = X[X['GrLivArea'] < 4500]

In [6]:
#синхронизируем данные
y = y[X.index]

In [7]:
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.1, random_state=SEED)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=(0.2/0.9), random_state=SEED)

In [8]:
numeric_colums = X_train.select_dtypes(include=['number']).columns
categorical_colums = X_train.select_dtypes(include=['object', 'string']).columns

In [ ]:
preprocessor = create_preprocessor(X_train, categorical_colums, numeric_colums)

In [10]:
preview_preprocessor = clone(preprocessor).set_output(transform='pandas')
X_encoded_preview = preview_preprocessor.fit_transform(X, y)
X_encoded_preview.head()

,Street_Pave,Alley_Grvl,Alley_Pave,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,Utilities_NoSeWa,...,PoolArea,MiscVal,MoSold,YrSold,HouseAge,RemodAge,TotalBath,HasGarage,HasBasement,TotalSF
0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,-1.601578,0.138375,-1.045249,-0.871676,1.174852,0.242536,0.161363,0.011436
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,-0.490155,-0.614427,-0.185182,0.388660,0.386571,0.242536,0.161363,-0.042838
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,0.991743,0.138375,-0.979090,-0.823201,1.174852,0.242536,0.161363,0.192351
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,-1.601578,-1.367230,1.799589,0.631032,-1.189990,0.242536,0.161363,-0.108743
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.063709,-0.087748,2.103167,0.138375,-0.946011,-0.726252,1.174852,0.242536,0.161363,1.015514

In [11]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [12]:
generator = torch.Generator().manual_seed(SEED)

# Применяем препроцессор
X_train_processed = preprocessor.fit_transform(X_train, y_train)
X_val_processed = preprocessor.transform(X_val)
X_test_processed = preprocessor.transform(X_test)

# Преобразуем данные в тензоры PyTorch
X_train_tensor = torch.tensor(X_train_processed, dtype=torch.float32).to(device)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1).to(device)

X_val_tensor = torch.tensor(X_val_processed, dtype=torch.float32).to(device)
y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32).unsqueeze(1)

X_test_tensor = torch.tensor(X_test_processed, dtype=torch.float32).to(device)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1).to(device)

# Создаем TensorDataset
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

# Создаем DataLoader'ы
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True, generator=generator)
val_loader = DataLoader(dataset=val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False)

c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [8, 9, 14, 15] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [13]:
#создаем модель 
class MyNN(nn.Module):
    def __init__(self, input, output):
        super().__init__()
        self.layer_1 = nn.Linear(input,128)
        self.batch_norm_1 = nn.BatchNorm1d(128)
        self.act_1 = nn.LeakyReLU()
        self.dropout_1 = nn.Dropout(0.4)
        self.layer_2 = nn.Linear(128,64)
        self.batch_norm_2 = nn.BatchNorm1d(64)
        self.act_2 = nn.ReLU()
        self.dropout_2 = nn.Dropout(0.2)
        self.layer_3 = nn.Linear(64,output)

    def forward(self,X):
        X = self.layer_1(X)
        X = self.batch_norm_1(X)
        X = self.act_1(X)
        X = self.dropout_1(X)
        X = self.layer_2(X)
        X = self.batch_norm_2(X)
        X = self.act_2(X)
        X = self.dropout_2(X)
        out = self.layer_3(X)
        return out

In [14]:
#объявляем модель
model = MyNN(X_train_processed.shape[1], 1).to(device)

In [15]:
# задаем оптимизатор и метрику
loss_reg = nn.MSELoss()
opt = torch.optim.AdamW(model.parameters(), lr=0.1, weight_decay=0.01)

In [16]:
# задаем шедулер
lr_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(opt,  #оптимизатор
                                                          mode = 'min',  #'max' или 'min' - следим чтобы отслеживаемый параметр увеличивался()
                                                          factor = 0.1,  #коэфициэнт, на который будет умножен lr
                                                          patience = 10, #кол-во эпох без улучшения отслеживаемого пораметров
                                                          eps = 1e-8,
                                                          )

In [17]:
#начинаем процесс обучения
EPOCHS = 500
train_loss = []
val_loss = []
lr_list = []
best_loss = None
best_model = 0
count = 0

for epoch in range(EPOCHS):
    model.train()
    train_loop = tqdm(train_loader,leave=False)
    running_train_loss = []
    for x,targets in train_loop:

        pred = model(x)
        loss = torch.sqrt(loss_reg(pred, targets))

        opt.zero_grad()
        loss.backward()

        opt.step()

        running_train_loss.append(loss.item())
        mean_train_loss = sum(running_train_loss)/len(running_train_loss)

        train_loop.set_description(f'Epoch[{epoch+1}/{EPOCHS}], train_loss = {mean_train_loss:.4f}')

    train_loss.append(mean_train_loss)

    model.eval()
    with torch.no_grad():
        running_val_loss = []
        for x, targets in val_loader:
            pred = model(x)
            loss = torch.sqrt(loss_reg(pred,targets))

            running_val_loss.append(loss.item())
            mean_val_loss = sum(running_val_loss)/len(running_val_loss)

        val_loss.append(mean_val_loss)

    lr_scheduler.step(mean_val_loss)

    lr = lr_scheduler._last_lr[0]
    lr_list.append(lr)
    print((f'Epoch [{epoch+1}/{EPOCHS}], train_loss = {mean_train_loss:.4f},  val_loss = {mean_val_loss:.4f}, lr = {lr:.4f}'))

    if best_loss is None:
      best_loss = mean_val_loss

    if mean_val_loss < best_loss:
      best_loss = mean_val_loss
      count = 0

      if best_model == 0:
        torch.save(model.state_dict(), f'best_nn_model/model_state_dict_epoch_{epoch+1}.pt')
        best_model = epoch+1

      else:
        os.remove(f'best_nn_model/model_state_dict_epoch_{best_model}.pt')
        torch.save(model.state_dict(), f'best_nn_model/model_state_dict_epoch_{epoch+1}.pt')
        best_model = epoch+1

      print(f'На эпохе - {epoch+1}, сохранена модель со значением функции потерь на валидации - {best_loss:.4f}', end='\n\n') 

    if count >= 150:
      print(f'\033[31Обучение остановлено на {epoch+1} эпохе.\033[0m')
      break
    count += 1

  0%|          | 0/32 [00:00<?, ?it/s]

Epoch [1/500], train_loss = 3.3895,  val_loss = 7.4272, lr = 0.1000

Epoch [2/500], train_loss = 1.5610,  val_loss = 2.1463, lr = 0.1000
На эпохе - 2, сохранена модель со значением функции потерь на валидации - 2.1463

Epoch [3/500], train_loss = 1.1921,  val_loss = 1.6000, lr = 0.1000
На эпохе - 3, сохранена модель со значением функции потерь на валидации - 1.6000

Epoch [4/500], train_loss = 1.1614,  val_loss = 0.9815, lr = 0.1000
На эпохе - 4, сохранена модель со значением функции потерь на валидации - 0.9815

Epoch [5/500], train_loss = 0.9749,  val_loss = 0.3541, lr = 0.1000
На эпохе - 5, сохранена модель со значением функции потерь на валидации - 0.3541

Epoch [6/500], train_loss = 0.8234,  val_loss = 0.5132, lr = 0.1000

Epoch [7/500], train_loss = 0.7812,  val_loss = 0.3448, lr = 0.1000
На эпохе - 7, сохранена модель со значением функции потерь на валидации - 0.3448

Epoch [8/500], train_loss = 0.7027,  val_loss = 0.2407, lr = 0.1000
На эпохе - 8, сохранена модель со значением функции потерь на валидации - 0.2407

Epoch [9/500], train_loss = 0.6582,  val_loss = 0.5437, lr = 0.1000

Epoch [10/500], train_loss = 0.6442,  val_loss = 0.3436, lr = 0.1000

Epoch [11/500], train_loss = 0.6297,  val_loss = 0.2475, lr = 0.1000

Epoch [12/500], train_loss = 0.7240,  val_loss = 0.4483, lr = 0.1000

Epoch [13/500], train_loss = 0.5715,  val_loss = 0.4722, lr = 0.1000

Epoch [14/500], train_loss = 0.5902,  val_loss = 0.2037, lr = 0.1000
На эпохе - 14, сохранена модель со значением функции потерь на валидации - 0.2037

Epoch [15/500], train_loss = 0.5175,  val_loss = 0.2078, lr = 0.1000

Epoch [16/500], train_loss = 0.4822,  val_loss = 0.1996, lr = 0.1000
На эпохе - 16, сохранена модель со значением функции потерь на валидации - 0.1996

Epoch [17/500], train_loss = 0.5567,  val_loss = 0.2072, lr = 0.1000

Epoch [18/500], train_loss = 0.5126,  val_loss = 0.4415, lr = 0.1000

Epoch [19/500], train_loss = 0.5478,  val_loss = 0.2651, lr = 0.1000

Epoch [20/500], train_loss = 0.4413,  val_loss = 0.1842, lr = 0.1000
На эпохе - 20, сохранена модель со значением функции потерь на валидации - 0.1842

Epoch [21/500], train_loss = 0.4649,  val_loss = 0.2493, lr = 0.1000

Epoch [22/500], train_loss = 0.5067,  val_loss = 0.2343, lr = 0.1000

Epoch [23/500], train_loss = 0.3818,  val_loss = 0.3847, lr = 0.1000

Epoch [24/500], train_loss = 0.4293,  val_loss = 0.1561, lr = 0.1000
На эпохе - 24, сохранена модель со значением функции потерь на валидации - 0.1561

Epoch [25/500], train_loss = 0.3419,  val_loss = 0.2114, lr = 0.1000

Epoch [26/500], train_loss = 0.3785,  val_loss = 0.2367, lr = 0.1000

Epoch [27/500], train_loss = 0.3528,  val_loss = 0.3428, lr = 0.1000

Epoch [28/500], train_loss = 0.3868,  val_loss = 0.6600, lr = 0.1000

Epoch [29/500], train_loss = 0.3354,  val_loss = 0.3054, lr = 0.1000

Epoch [30/500], train_loss = 0.3685,  val_loss = 0.2147, lr = 0.1000

Epoch [31/500], train_loss = 0.2782,  val_loss = 0.2669, lr = 0.1000

Epoch [32/500], train_loss = 0.3132,  val_loss = 0.2312, lr = 0.1000

Epoch [33/500], train_loss = 0.2993,  val_loss = 0.2705, lr = 0.1000

Epoch [34/500], train_loss = 0.2642,  val_loss = 0.4256, lr = 0.1000

Epoch [35/500], train_loss = 0.2904,  val_loss = 0.1883, lr = 0.0100

Epoch [36/500], train_loss = 0.2234,  val_loss = 0.1590, lr = 0.0100

Epoch [37/500], train_loss = 0.1999,  val_loss = 0.1523, lr = 0.0100
На эпохе - 37, сохранена модель со значением функции потерь на валидации - 0.1523

Epoch [38/500], train_loss = 0.2084,  val_loss = 0.1469, lr = 0.0100
На эпохе - 38, сохранена модель со значением функции потерь на валидации - 0.1469

Epoch [39/500], train_loss = 0.2000,  val_loss = 0.1851, lr = 0.0100

Epoch [40/500], train_loss = 0.2101,  val_loss = 0.1773, lr = 0.0100

Epoch [41/500], train_loss = 0.1966,  val_loss = 0.1404, lr = 0.0100
На эпохе - 41, сохранена модель со значением функции потерь на валидации - 0.1404

Epoch [42/500], train_loss = 0.2079,  val_loss = 0.1560, lr = 0.0100

Epoch [43/500], train_loss = 0.2058,  val_loss = 0.1513, lr = 0.0100

Epoch [44/500], train_loss = 0.1919,  val_loss = 0.1631, lr = 0.0100

Epoch [45/500], train_loss = 0.2022,  val_loss = 0.1387, lr = 0.0100
На эпохе - 45, сохранена модель со значением функции потерь на валидации - 0.1387

Epoch [46/500], train_loss = 0.2085,  val_loss = 0.1580, lr = 0.0100

Epoch [47/500], train_loss = 0.1975,  val_loss = 0.1349, lr = 0.0100
На эпохе - 47, сохранена модель со значением функции потерь на валидации - 0.1349

Epoch [48/500], train_loss = 0.2004,  val_loss = 0.1620, lr = 0.0100

Epoch [49/500], train_loss = 0.2118,  val_loss = 0.1606, lr = 0.0100

Epoch [50/500], train_loss = 0.1985,  val_loss = 0.1421, lr = 0.0100

Epoch [51/500], train_loss = 0.2147,  val_loss = 0.1805, lr = 0.0100

Epoch [52/500], train_loss = 0.2078,  val_loss = 0.1514, lr = 0.0100

Epoch [53/500], train_loss = 0.2087,  val_loss = 0.1411, lr = 0.0100

Epoch [54/500], train_loss = 0.1903,  val_loss = 0.1477, lr = 0.0100

Epoch [55/500], train_loss = 0.2239,  val_loss = 0.1311, lr = 0.0100
На эпохе - 55, сохранена модель со значением функции потерь на валидации - 0.1311

Epoch [56/500], train_loss = 0.2004,  val_loss = 0.1407, lr = 0.0100

Epoch [57/500], train_loss = 0.1898,  val_loss = 0.1435, lr = 0.0100

Epoch [58/500], train_loss = 0.2073,  val_loss = 0.1375, lr = 0.0100

Epoch [59/500], train_loss = 0.1933,  val_loss = 0.1350, lr = 0.0100

Epoch [60/500], train_loss = 0.1810,  val_loss = 0.1348, lr = 0.0100

Epoch [61/500], train_loss = 0.1987,  val_loss = 0.1377, lr = 0.0100

Epoch [62/500], train_loss = 0.1965,  val_loss = 0.1426, lr = 0.0100

Epoch [63/500], train_loss = 0.1920,  val_loss = 0.1376, lr = 0.0100

Epoch [64/500], train_loss = 0.2017,  val_loss = 0.1669, lr = 0.0100

Epoch [65/500], train_loss = 0.1899,  val_loss = 0.1346, lr = 0.0100

Epoch [66/500], train_loss = 0.1975,  val_loss = 0.1715, lr = 0.0010

Epoch [67/500], train_loss = 0.1958,  val_loss = 0.1392, lr = 0.0010

Epoch [68/500], train_loss = 0.1997,  val_loss = 0.1397, lr = 0.0010

Epoch [69/500], train_loss = 0.1928,  val_loss = 0.1343, lr = 0.0010

Epoch [70/500], train_loss = 0.1914,  val_loss = 0.1387, lr = 0.0010

Epoch [71/500], train_loss = 0.1899,  val_loss = 0.1388, lr = 0.0010

Epoch [72/500], train_loss = 0.1924,  val_loss = 0.1301, lr = 0.0010
На эпохе - 72, сохранена модель со значением функции потерь на валидации - 0.1301

Epoch [73/500], train_loss = 0.1777,  val_loss = 0.1347, lr = 0.0010

Epoch [74/500], train_loss = 0.1766,  val_loss = 0.1332, lr = 0.0010

Epoch [75/500], train_loss = 0.1863,  val_loss = 0.1444, lr = 0.0010

Epoch [76/500], train_loss = 0.1871,  val_loss = 0.1320, lr = 0.0010

Epoch [77/500], train_loss = 0.1772,  val_loss = 0.1364, lr = 0.0010

Epoch [78/500], train_loss = 0.1831,  val_loss = 0.1369, lr = 0.0010

Epoch [79/500], train_loss = 0.1919,  val_loss = 0.1373, lr = 0.0010

Epoch [80/500], train_loss = 0.1786,  val_loss = 0.1357, lr = 0.0010

Epoch [81/500], train_loss = 0.1819,  val_loss = 0.1340, lr = 0.0010

Epoch [82/500], train_loss = 0.1896,  val_loss = 0.1337, lr = 0.0010

Epoch [83/500], train_loss = 0.1789,  val_loss = 0.1322, lr = 0.0001

Epoch [84/500], train_loss = 0.1801,  val_loss = 0.1315, lr = 0.0001

Epoch [85/500], train_loss = 0.1844,  val_loss = 0.1372, lr = 0.0001

Epoch [86/500], train_loss = 0.1805,  val_loss = 0.1354, lr = 0.0001

Epoch [87/500], train_loss = 0.1852,  val_loss = 0.1342, lr = 0.0001

Epoch [88/500], train_loss = 0.1858,  val_loss = 0.1344, lr = 0.0001

Epoch [89/500], train_loss = 0.1900,  val_loss = 0.1344, lr = 0.0001

Epoch [90/500], train_loss = 0.1822,  val_loss = 0.1357, lr = 0.0001

Epoch [91/500], train_loss = 0.1803,  val_loss = 0.1379, lr = 0.0001

Epoch [92/500], train_loss = 0.1821,  val_loss = 0.1326, lr = 0.0001

Epoch [93/500], train_loss = 0.1863,  val_loss = 0.1362, lr = 0.0001

Epoch [94/500], train_loss = 0.1782,  val_loss = 0.1320, lr = 0.0000

Epoch [95/500], train_loss = 0.1780,  val_loss = 0.1399, lr = 0.0000

Epoch [96/500], train_loss = 0.1866,  val_loss = 0.1405, lr = 0.0000

Epoch [97/500], train_loss = 0.1832,  val_loss = 0.1337, lr = 0.0000

Epoch [98/500], train_loss = 0.1759,  val_loss = 0.1441, lr = 0.0000

Epoch [99/500], train_loss = 0.1855,  val_loss = 0.1358, lr = 0.0000

Epoch [100/500], train_loss = 0.1766,  val_loss = 0.1360, lr = 0.0000

Epoch [101/500], train_loss = 0.1834,  val_loss = 0.1376, lr = 0.0000

Epoch [102/500], train_loss = 0.1824,  val_loss = 0.1379, lr = 0.0000

Epoch [103/500], train_loss = 0.1771,  val_loss = 0.1336, lr = 0.0000

Epoch [104/500], train_loss = 0.1858,  val_loss = 0.1345, lr = 0.0000

Epoch [105/500], train_loss = 0.1838,  val_loss = 0.1340, lr = 0.0000

Epoch [106/500], train_loss = 0.1843,  val_loss = 0.1366, lr = 0.0000

Epoch [107/500], train_loss = 0.1858,  val_loss = 0.1351, lr = 0.0000

Epoch [108/500], train_loss = 0.1784,  val_loss = 0.1337, lr = 0.0000

Epoch [109/500], train_loss = 0.1863,  val_loss = 0.1351, lr = 0.0000

Epoch [110/500], train_loss = 0.1803,  val_loss = 0.1370, lr = 0.0000

Epoch [111/500], train_loss = 0.1848,  val_loss = 0.1344, lr = 0.0000

Epoch [112/500], train_loss = 0.1847,  val_loss = 0.1371, lr = 0.0000

Epoch [113/500], train_loss = 0.1864,  val_loss = 0.1322, lr = 0.0000

Epoch [114/500], train_loss = 0.1834,  val_loss = 0.1383, lr = 0.0000

Epoch [115/500], train_loss = 0.1878,  val_loss = 0.1368, lr = 0.0000

Epoch [116/500], train_loss = 0.1858,  val_loss = 0.1338, lr = 0.0000

Epoch [117/500], train_loss = 0.1774,  val_loss = 0.1340, lr = 0.0000

Epoch [118/500], train_loss = 0.1843,  val_loss = 0.1381, lr = 0.0000

Epoch [119/500], train_loss = 0.1890,  val_loss = 0.1301, lr = 0.0000

Epoch [120/500], train_loss = 0.1768,  val_loss = 0.1327, lr = 0.0000

Epoch [121/500], train_loss = 0.1883,  val_loss = 0.1363, lr = 0.0000

Epoch [122/500], train_loss = 0.1835,  val_loss = 0.1336, lr = 0.0000

Epoch [123/500], train_loss = 0.1873,  val_loss = 0.1343, lr = 0.0000

Epoch [124/500], train_loss = 0.1769,  val_loss = 0.1371, lr = 0.0000

Epoch [125/500], train_loss = 0.1846,  val_loss = 0.1373, lr = 0.0000

Epoch [126/500], train_loss = 0.1835,  val_loss = 0.1359, lr = 0.0000

Epoch [127/500], train_loss = 0.1870,  val_loss = 0.1311, lr = 0.0000

Epoch [128/500], train_loss = 0.1944,  val_loss = 0.1363, lr = 0.0000

Epoch [129/500], train_loss = 0.1774,  val_loss = 0.1374, lr = 0.0000

Epoch [130/500], train_loss = 0.1802,  val_loss = 0.1371, lr = 0.0000

Epoch [131/500], train_loss = 0.1856,  val_loss = 0.1366, lr = 0.0000

Epoch [132/500], train_loss = 0.1785,  val_loss = 0.1358, lr = 0.0000

Epoch [133/500], train_loss = 0.1820,  val_loss = 0.1329, lr = 0.0000

Epoch [134/500], train_loss = 0.1818,  val_loss = 0.1352, lr = 0.0000

Epoch [135/500], train_loss = 0.1850,  val_loss = 0.1401, lr = 0.0000

Epoch [136/500], train_loss = 0.1919,  val_loss = 0.1370, lr = 0.0000

Epoch [137/500], train_loss = 0.1784,  val_loss = 0.1332, lr = 0.0000

Epoch [138/500], train_loss = 0.1763,  val_loss = 0.1369, lr = 0.0000

Epoch [139/500], train_loss = 0.1841,  val_loss = 0.1335, lr = 0.0000

Epoch [140/500], train_loss = 0.1805,  val_loss = 0.1350, lr = 0.0000

Epoch [141/500], train_loss = 0.1867,  val_loss = 0.1319, lr = 0.0000

Epoch [142/500], train_loss = 0.1785,  val_loss = 0.1377, lr = 0.0000

Epoch [143/500], train_loss = 0.1802,  val_loss = 0.1393, lr = 0.0000

Epoch [144/500], train_loss = 0.1812,  val_loss = 0.1361, lr = 0.0000

Epoch [145/500], train_loss = 0.1842,  val_loss = 0.1362, lr = 0.0000

Epoch [146/500], train_loss = 0.1863,  val_loss = 0.1417, lr = 0.0000

Epoch [147/500], train_loss = 0.1788,  val_loss = 0.1377, lr = 0.0000

Epoch [148/500], train_loss = 0.1841,  val_loss = 0.1365, lr = 0.0000

Epoch [149/500], train_loss = 0.1961,  val_loss = 0.1301, lr = 0.0000

Epoch [150/500], train_loss = 0.1832,  val_loss = 0.1355, lr = 0.0000

Epoch [151/500], train_loss = 0.1857,  val_loss = 0.1320, lr = 0.0000

Epoch [152/500], train_loss = 0.1925,  val_loss = 0.1423, lr = 0.0000

Epoch [153/500], train_loss = 0.1769,  val_loss = 0.1346, lr = 0.0000

Epoch [154/500], train_loss = 0.1821,  val_loss = 0.1355, lr = 0.0000

Epoch [155/500], train_loss = 0.1799,  val_loss = 0.1351, lr = 0.0000

Epoch [156/500], train_loss = 0.1788,  val_loss = 0.1337, lr = 0.0000

Epoch [157/500], train_loss = 0.1747,  val_loss = 0.1394, lr = 0.0000

Epoch [158/500], train_loss = 0.1801,  val_loss = 0.1352, lr = 0.0000

Epoch [159/500], train_loss = 0.1821,  val_loss = 0.1325, lr = 0.0000

Epoch [160/500], train_loss = 0.1806,  val_loss = 0.1332, lr = 0.0000

Epoch [161/500], train_loss = 0.1934,  val_loss = 0.1374, lr = 0.0000

Epoch [162/500], train_loss = 0.1812,  val_loss = 0.1333, lr = 0.0000

Epoch [163/500], train_loss = 0.1753,  val_loss = 0.1328, lr = 0.0000

Epoch [164/500], train_loss = 0.1819,  val_loss = 0.1317, lr = 0.0000

Epoch [165/500], train_loss = 0.1815,  val_loss = 0.1337, lr = 0.0000

Epoch [166/500], train_loss = 0.1822,  val_loss = 0.1323, lr = 0.0000

Epoch [167/500], train_loss = 0.1836,  val_loss = 0.1357, lr = 0.0000

Epoch [168/500], train_loss = 0.1948,  val_loss = 0.1315, lr = 0.0000

Epoch [169/500], train_loss = 0.1909,  val_loss = 0.1347, lr = 0.0000

Epoch [170/500], train_loss = 0.1824,  val_loss = 0.1323, lr = 0.0000

Epoch [171/500], train_loss = 0.1820,  val_loss = 0.1377, lr = 0.0000

Epoch [172/500], train_loss = 0.1762,  val_loss = 0.1332, lr = 0.0000

Epoch [173/500], train_loss = 0.1922,  val_loss = 0.1359, lr = 0.0000

Epoch [174/500], train_loss = 0.1864,  val_loss = 0.1327, lr = 0.0000

Epoch [175/500], train_loss = 0.1833,  val_loss = 0.1364, lr = 0.0000

Epoch [176/500], train_loss = 0.1870,  val_loss = 0.1352, lr = 0.0000

Epoch [177/500], train_loss = 0.1741,  val_loss = 0.1353, lr = 0.0000

Epoch [178/500], train_loss = 0.1865,  val_loss = 0.1315, lr = 0.0000

Epoch [179/500], train_loss = 0.1755,  val_loss = 0.1363, lr = 0.0000

Epoch [180/500], train_loss = 0.1872,  val_loss = 0.1347, lr = 0.0000

Epoch [181/500], train_loss = 0.1779,  val_loss = 0.1383, lr = 0.0000

Epoch [182/500], train_loss = 0.1827,  val_loss = 0.1370, lr = 0.0000

Epoch [183/500], train_loss = 0.1839,  val_loss = 0.1396, lr = 0.0000

Epoch [184/500], train_loss = 0.1894,  val_loss = 0.1333, lr = 0.0000

Epoch [185/500], train_loss = 0.1835,  val_loss = 0.1340, lr = 0.0000

Epoch [186/500], train_loss = 0.1828,  val_loss = 0.1426, lr = 0.0000

Epoch [187/500], train_loss = 0.1875,  val_loss = 0.1348, lr = 0.0000

Epoch [188/500], train_loss = 0.1860,  val_loss = 0.1342, lr = 0.0000

Epoch [189/500], train_loss = 0.1838,  val_loss = 0.1387, lr = 0.0000

Epoch [190/500], train_loss = 0.1831,  val_loss = 0.1390, lr = 0.0000

Epoch [191/500], train_loss = 0.1797,  val_loss = 0.1362, lr = 0.0000

Epoch [192/500], train_loss = 0.1819,  val_loss = 0.1318, lr = 0.0000

Epoch [193/500], train_loss = 0.1911,  val_loss = 0.1316, lr = 0.0000

Epoch [194/500], train_loss = 0.1890,  val_loss = 0.1359, lr = 0.0000

Epoch [195/500], train_loss = 0.1822,  val_loss = 0.1391, lr = 0.0000

Epoch [196/500], train_loss = 0.1765,  val_loss = 0.1341, lr = 0.0000

Epoch [197/500], train_loss = 0.1836,  val_loss = 0.1319, lr = 0.0000

Epoch [198/500], train_loss = 0.1822,  val_loss = 0.1337, lr = 0.0000

Epoch [199/500], train_loss = 0.1772,  val_loss = 0.1343, lr = 0.0000

Epoch [200/500], train_loss = 0.1881,  val_loss = 0.1367, lr = 0.0000

Epoch [201/500], train_loss = 0.1918,  val_loss = 0.1362, lr = 0.0000

Epoch [202/500], train_loss = 0.1833,  val_loss = 0.1359, lr = 0.0000

Epoch [203/500], train_loss = 0.1926,  val_loss = 0.1424, lr = 0.0000

Epoch [204/500], train_loss = 0.1884,  val_loss = 0.1323, lr = 0.0000

Epoch [205/500], train_loss = 0.1831,  val_loss = 0.1329, lr = 0.0000

Epoch [206/500], train_loss = 0.1857,  val_loss = 0.1355, lr = 0.0000

Epoch [207/500], train_loss = 0.1812,  val_loss = 0.1364, lr = 0.0000

Epoch [208/500], train_loss = 0.1780,  val_loss = 0.1329, lr = 0.0000

Epoch [209/500], train_loss = 0.1805,  val_loss = 0.1390, lr = 0.0000

Epoch [210/500], train_loss = 0.1851,  val_loss = 0.1370, lr = 0.0000

Epoch [211/500], train_loss = 0.1748,  val_loss = 0.1408, lr = 0.0000

Epoch [212/500], train_loss = 0.1807,  val_loss = 0.1331, lr = 0.0000

Epoch [213/500], train_loss = 0.1797,  val_loss = 0.1376, lr = 0.0000

Epoch [214/500], train_loss = 0.1746,  val_loss = 0.1372, lr = 0.0000

Epoch [215/500], train_loss = 0.1932,  val_loss = 0.1307, lr = 0.0000

Epoch [216/500], train_loss = 0.1913,  val_loss = 0.1365, lr = 0.0000

Epoch [217/500], train_loss = 0.1830,  val_loss = 0.1306, lr = 0.0000

Epoch [218/500], train_loss = 0.1873,  val_loss = 0.1316, lr = 0.0000

Epoch [219/500], train_loss = 0.1857,  val_loss = 0.1377, lr = 0.0000

Epoch [220/500], train_loss = 0.1893,  val_loss = 0.1356, lr = 0.0000

Epoch [221/500], train_loss = 0.1922,  val_loss = 0.1312, lr = 0.0000

Epoch [222/500], train_loss = 0.1863,  val_loss = 0.1383, lr = 0.0000
[31Обучение остановлено на 222 эпохе.

In [18]:
# загружаем веса лучшей модели и начинаем процесс тестирования
model.load_state_dict(torch.load(f'best_nn_model/model_state_dict_epoch_{best_model}.pt'))

model.eval()
with torch.no_grad():
    running_test_loss = []
    for x, targets in test_loader:
        pred = model(x)
        loss = torch.sqrt(loss_reg(pred,targets))
        running_test_loss.append(loss.item())

    mean_test_loss = sum(running_test_loss)/len(running_test_loss)
    print(f'Финальный loss = {mean_test_loss:.4f}')

Финальный loss = 0.1104

In [ ]:
# 2. Загружаем тестовый набор данных 
test_data = pd.read_csv('data/test.csv')
test_ids = test_data['Id']

# 3. Предобработка тестовых данных
X_test_final = engineer_features(test_data)
X_test_processed_final = preprocessor.transform(X_test_final)

# Конвертируем в тензор
X_test_tensor_final = torch.tensor(X_test_processed_final, dtype=torch.float32).to(device)

print("Данные готовы к предсказанию.")

c:\Users\angelika\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [4, 8, 11] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

Данные готовы к предсказанию.

In [20]:
model.eval()
with torch.no_grad():
    # Получаем предсказания
    log_preds = model(X_test_tensor_final).numpy().flatten()

# Переводим из логарифмического масштаба обратно
final_preds = np.expm1(log_preds)

# Создаем DataFrame для отправки
submission = pd.DataFrame({
    'Id': test_ids,
    'SalePrice': final_preds
})

# Сохраняем в CSV
submission.to_csv('data/nn_submission/submission.csv', index=False)

print("Файл submission.csv успешно создан!")
display(submission.head(30))

Файл submission.csv успешно создан!

      Id      SalePrice
0   1461  118889.351562
1   1462  173251.890625
2   1463  182229.484375
3   1464  192859.718750
4   1465  186539.921875
5   1466  176247.781250
6   1467  179101.000000
7   1468  168498.656250
8   1469  188803.984375
9   1470  122951.335938
10  1471  188493.093750
11  1472   92279.632812
12  1473   93326.539062
13  1474  148327.484375
14  1475  109857.750000
15  1476  378023.156250
16  1477  259433.609375
17  1478  279369.125000
18  1479  268663.531250
19  1480  560586.187500
20  1481  324141.062500
21  1482  203736.640625
22  1483  169991.312500
23  1484  158344.734375
24  1485  185543.687500
25  1486  193910.578125
26  1487  334199.281250
27  1488  226115.343750
28  1489  196054.937500
29  1490  234329.250000